// GENERATED by cicada_generator/tool/generate_crosswalk_maps.py from
// crosswalk/observation_crosswalk.json — do not edit by hand.
//
// CDC's supporting data carries SNOMED, CVX and PHIN VS only, so every
// ICD-10-CM code here is ours. The hand-written version carried 17 elements.
Instance: Icd10ToCdsiObservation
InstanceOf: ConceptMap
Usage: #definition
Title: "ICD-10-CM to CDSi Observation Code Map"
Description: "Maps ICD-10-CM codes to CDSi observation codes used in immunization decision support. Generated from the cicada crosswalk."
* status = #active
* experimental = false
// ValueSets, not CodeSystems: R4 binds ConceptMap.source[x] to a ValueSet.
* sourceCanonical = "http://fhirfli.dev/fhir/ig/cicada/ValueSet/vaccine-condition-codes-icd10"
* targetCanonical = "http://fhirfli.dev/fhir/ig/cicada/ValueSet/cdsi-observation-codes-vs"

* group[+].source = "http://hl7.org/fhir/sid/icd-10-cm"
* group[=].target = "http://fhirfli.dev/fhir/ig/cicada/CodeSystem/cdsi-observation-codes"

// 003 - Immunocompromised
* group[=].element[+].code = #D84.9
* group[=].element[=].display = "Immunodeficiency, unspecified"
* group[=].element[=].target[+].code = #003
* group[=].element[=].target[=].display = "Immunocompromised"
* group[=].element[=].target[=].equivalence = #equivalent

// 003 - Immunocompromised
* group[=].element[+].code = #D83.9
* group[=].element[=].display = "Common variable immunodeficiency, unspecified"
* group[=].element[=].target[+].code = #003
* group[=].element[=].target[=].display = "Immunocompromised"
* group[=].element[=].target[=].equivalence = #equivalent

// 003 - Immunocompromised
* group[=].element[+].code = #D80.9
* group[=].element[=].display = "Immunodeficiency with predominantly antibody defects, unspecified"
* group[=].element[=].target[+].code = #003
* group[=].element[=].target[=].display = "Immunocompromised"
* group[=].element[=].target[=].equivalence = #equivalent

// 003 - Immunocompromised
* group[=].element[+].code = #D89.9
* group[=].element[=].display = "Disorder involving the immune mechanism, unspecified"
* group[=].element[=].target[+].code = #003
* group[=].element[=].target[=].display = "Immunocompromised"
* group[=].element[=].target[=].equivalence = #equivalent

// 003 - Immunocompromised
* group[=].element[+].code = #D84.8
* group[=].element[=].display = "Other specified immunodeficiencies"
* group[=].element[=].target[+].code = #003
* group[=].element[=].target[=].display = "Immunocompromised"
* group[=].element[=].target[=].equivalence = #equivalent

// 004 - Recipient of a hematopoietic stem cell transplant
* group[=].element[+].code = #Z94.84
* group[=].element[=].display = "Stem cells transplant status"
* group[=].element[=].target[+].code = #004
* group[=].element[=].target[=].display = "Recipient of a hematopoietic stem cell transplant"
* group[=].element[=].target[=].equivalence = #equivalent

// 004 - Recipient of a hematopoietic stem cell transplant
* group[=].element[+].code = #T86.00
* group[=].element[=].display = "Unspecified complication of bone marrow transplant"
* group[=].element[=].target[+].code = #004
* group[=].element[=].target[=].display = "Recipient of a hematopoietic stem cell transplant"
* group[=].element[=].target[=].equivalence = #equivalent

// 004 - Recipient of a hematopoietic stem cell transplant
* group[=].element[+].code = #T86.09
* group[=].element[=].display = "Other complications of bone marrow transplant"
* group[=].element[=].target[+].code = #004
* group[=].element[=].target[=].display = "Recipient of a hematopoietic stem cell transplant"
* group[=].element[=].target[=].equivalence = #equivalent

// 005 - Hepatitis C virus infection
* group[=].element[+].code = #B18.2
* group[=].element[=].display = "Chronic viral hepatitis C"
* group[=].element[=].target[+].code = #005
* group[=].element[=].target[=].display = "Hepatitis C virus infection"
* group[=].element[=].target[=].equivalence = #equivalent

// 005 - Hepatitis C virus infection
* group[=].element[+].code = #B17.10
* group[=].element[=].display = "Acute hepatitis C without hepatic coma"
* group[=].element[=].target[+].code = #005
* group[=].element[=].target[=].display = "Hepatitis C virus infection"
* group[=].element[=].target[=].equivalence = #equivalent

// 005 - Hepatitis C virus infection
* group[=].element[+].code = #B17.11
* group[=].element[=].display = "Acute hepatitis C with hepatic coma"
* group[=].element[=].target[+].code = #005
* group[=].element[=].target[=].display = "Hepatitis C virus infection"
* group[=].element[=].target[=].equivalence = #equivalent

// 005 - Hepatitis C virus infection
* group[=].element[+].code = #B19.20
* group[=].element[=].display = "Unspecified viral hepatitis C without hepatic coma"
* group[=].element[=].target[+].code = #005
* group[=].element[=].target[=].display = "Hepatitis C virus infection"
* group[=].element[=].target[=].equivalence = #equivalent

// 006 - Receives clotting factor concentrates
* group[=].element[+].code = #D66
* group[=].element[=].display = "Hereditary factor VIII deficiency"
* group[=].element[=].target[+].code = #006
* group[=].element[=].target[=].display = "Receives clotting factor concentrates"
* group[=].element[=].target[=].equivalence = #equivalent

// 006 - Receives clotting factor concentrates
* group[=].element[+].code = #D67
* group[=].element[=].display = "Hereditary factor IX deficiency"
* group[=].element[=].target[+].code = #006
* group[=].element[=].target[=].display = "Receives clotting factor concentrates"
* group[=].element[=].target[=].equivalence = #equivalent

// 006 - Receives clotting factor concentrates
* group[=].element[+].code = #D68.2
* group[=].element[=].display = "Hereditary deficiency of other clotting factors"
* group[=].element[=].target[+].code = #006
* group[=].element[=].target[=].display = "Receives clotting factor concentrates"
* group[=].element[=].target[=].equivalence = #equivalent

// 007 - Pregnant
* group[=].element[+].code = #Z33.1
* group[=].element[=].display = "Pregnant state, incidental"
* group[=].element[=].target[+].code = #007
* group[=].element[=].target[=].display = "Pregnant"
* group[=].element[=].target[=].equivalence = #equivalent

// 007 - Pregnant
* group[=].element[+].code = #O09.90
* group[=].element[=].display = "Supervision of high risk pregnancy, unspecified, unspecified trimester"
* group[=].element[=].target[+].code = #007
* group[=].element[=].target[=].display = "Pregnant"
* group[=].element[=].target[=].equivalence = #equivalent

// 007 - Pregnant
* group[=].element[+].code = #Z34.00
* group[=].element[=].display = "Encounter for supervision of normal first pregnancy, unspecified trimester"
* group[=].element[=].target[+].code = #007
* group[=].element[=].target[=].display = "Pregnant"
* group[=].element[=].target[=].equivalence = #equivalent

// 007 - Pregnant
* group[=].element[+].code = #Z34.80
* group[=].element[=].display = "Encounter for supervision of other normal pregnancy, unspecified trimester"
* group[=].element[=].target[+].code = #007
* group[=].element[=].target[=].display = "Pregnant"
* group[=].element[=].target[=].equivalence = #equivalent

// 009 - Breastfeeding
* group[=].element[+].code = #Z39.1
* group[=].element[=].display = "Encounter for care and examination of lactating mother"
* group[=].element[=].target[+].code = #009
* group[=].element[=].target[=].display = "Breastfeeding"
* group[=].element[=].target[=].equivalence = #equivalent

// 010 - Cerebrospinal fluid leaks
* group[=].element[+].code = #G96.00
* group[=].element[=].display = "Cerebrospinal fluid leak, unspecified"
* group[=].element[=].target[+].code = #010
* group[=].element[=].target[=].display = "Cerebrospinal fluid leaks"
* group[=].element[=].target[=].equivalence = #equivalent

// 010 - Cerebrospinal fluid leaks
* group[=].element[+].code = #G96.01
* group[=].element[=].display = "Cranial cerebrospinal fluid leak, spontaneous"
* group[=].element[=].target[+].code = #010
* group[=].element[=].target[=].display = "Cerebrospinal fluid leaks"
* group[=].element[=].target[=].equivalence = #equivalent

// 010 - Cerebrospinal fluid leaks
* group[=].element[+].code = #G96.02
* group[=].element[=].display = "Spinal cerebrospinal fluid leak, spontaneous"
* group[=].element[=].target[+].code = #010
* group[=].element[=].target[=].display = "Cerebrospinal fluid leaks"
* group[=].element[=].target[=].equivalence = #equivalent

// 010 - Cerebrospinal fluid leaks
* group[=].element[+].code = #G96.08
* group[=].element[=].display = "Other cranial cerebrospinal fluid leak"
* group[=].element[=].target[+].code = #010
* group[=].element[=].target[=].display = "Cerebrospinal fluid leaks"
* group[=].element[=].target[=].equivalence = #equivalent

// 010 - Cerebrospinal fluid leaks
* group[=].element[+].code = #G96.09
* group[=].element[=].display = "Other spinal cerebrospinal fluid leak"
* group[=].element[=].target[+].code = #010
* group[=].element[=].target[=].display = "Cerebrospinal fluid leaks"
* group[=].element[=].target[=].equivalence = #equivalent

// 011 - Cochlear implants
* group[=].element[+].code = #Z96.21
* group[=].element[=].display = "Cochlear implant status"
* group[=].element[=].target[+].code = #011
* group[=].element[=].target[=].display = "Cochlear implants"
* group[=].element[=].target[=].equivalence = #equivalent

// 012 - Family history of altered immunocompetence
* group[=].element[+].code = #Z83.2
* group[=].element[=].display = "Family history of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism"
* group[=].element[=].target[+].code = #012
* group[=].element[=].target[=].display = "Family history of altered immunocompetence"
* group[=].element[=].target[=].equivalence = #equivalent

// 013 - Severe Combined Immunodeficiency [SCID]
* group[=].element[+].code = #D81.9
* group[=].element[=].display = "Combined immunodeficiency, unspecified"
* group[=].element[=].target[+].code = #013
* group[=].element[=].target[=].display = "Severe Combined Immunodeficiency [SCID]"
* group[=].element[=].target[=].equivalence = #equivalent

// 013 - Severe Combined Immunodeficiency [SCID]
* group[=].element[+].code = #D81.0
* group[=].element[=].display = "Severe combined immunodeficiency [SCID] with reticular dysgenesis"
* group[=].element[=].target[+].code = #013
* group[=].element[=].target[=].display = "Severe Combined Immunodeficiency [SCID]"
* group[=].element[=].target[=].equivalence = #equivalent

// 013 - Severe Combined Immunodeficiency [SCID]
* group[=].element[+].code = #D81.1
* group[=].element[=].display = "Severe combined immunodeficiency [SCID] with low T- and B-cell numbers"
* group[=].element[=].target[+].code = #013
* group[=].element[=].target[=].display = "Severe Combined Immunodeficiency [SCID]"
* group[=].element[=].target[=].equivalence = #equivalent

// 013 - Severe Combined Immunodeficiency [SCID]
* group[=].element[+].code = #D81.2
* group[=].element[=].display = "Severe combined immunodeficiency [SCID] with low or normal B-cell numbers"
* group[=].element[=].target[+].code = #013
* group[=].element[=].target[=].display = "Severe Combined Immunodeficiency [SCID]"
* group[=].element[=].target[=].equivalence = #equivalent

// 013 - Severe Combined Immunodeficiency [SCID]
* group[=].element[+].code = #D81.3
* group[=].element[=].display = "Adenosine deaminase [ADA] deficiency"
* group[=].element[=].target[+].code = #013
* group[=].element[=].target[=].display = "Severe Combined Immunodeficiency [SCID]"
* group[=].element[=].target[=].equivalence = #equivalent

// 013 - Severe Combined Immunodeficiency [SCID]
* group[=].element[+].code = #D81.5
* group[=].element[=].display = "Purine nucleoside phosphorylase [PNP] deficiency"
* group[=].element[=].target[+].code = #013
* group[=].element[=].target[=].display = "Severe Combined Immunodeficiency [SCID]"
* group[=].element[=].target[=].equivalence = #equivalent

// 013 - Severe Combined Immunodeficiency [SCID]
* group[=].element[+].code = #D81.6
* group[=].element[=].display = "Major histocompatibility complex class I deficiency"
* group[=].element[=].target[+].code = #013
* group[=].element[=].target[=].display = "Severe Combined Immunodeficiency [SCID]"
* group[=].element[=].target[=].equivalence = #equivalent

// 013 - Severe Combined Immunodeficiency [SCID]
* group[=].element[+].code = #D81.7
* group[=].element[=].display = "Major histocompatibility complex class II deficiency"
* group[=].element[=].target[+].code = #013
* group[=].element[=].target[=].display = "Severe Combined Immunodeficiency [SCID]"
* group[=].element[=].target[=].equivalence = #equivalent

// 014 - Diabetes
* group[=].element[+].code = #E10.9
* group[=].element[=].display = "Type 1 diabetes mellitus without complications"
* group[=].element[=].target[+].code = #014
* group[=].element[=].target[=].display = "Diabetes"
* group[=].element[=].target[=].equivalence = #equivalent

// 014 - Diabetes
* group[=].element[+].code = #E10.65
* group[=].element[=].display = "Type 1 diabetes mellitus with hyperglycemia"
* group[=].element[=].target[+].code = #014
* group[=].element[=].target[=].display = "Diabetes"
* group[=].element[=].target[=].equivalence = #equivalent

// 014 - Diabetes
* group[=].element[+].code = #E11.9
* group[=].element[=].display = "Type 2 diabetes mellitus without complications"
* group[=].element[=].target[+].code = #014
* group[=].element[=].target[=].display = "Diabetes"
* group[=].element[=].target[=].equivalence = #equivalent

// 014 - Diabetes
* group[=].element[+].code = #E11.65
* group[=].element[=].display = "Type 2 diabetes mellitus with hyperglycemia"
* group[=].element[=].target[+].code = #014
* group[=].element[=].target[=].display = "Diabetes"
* group[=].element[=].target[=].equivalence = #equivalent

// 014 - Diabetes
* group[=].element[+].code = #E13.9
* group[=].element[=].display = "Other specified diabetes mellitus without complications"
* group[=].element[=].target[+].code = #014
* group[=].element[=].target[=].display = "Diabetes"
* group[=].element[=].target[=].equivalence = #equivalent

// 014 - Diabetes
* group[=].element[+].code = #E08.9
* group[=].element[=].display = "Diabetes mellitus due to underlying condition without complications"
* group[=].element[=].target[+].code = #014
* group[=].element[=].target[=].display = "Diabetes"
* group[=].element[=].target[=].equivalence = #equivalent

// 014 - Diabetes
* group[=].element[+].code = #E09.9
* group[=].element[=].display = "Drug or chemical induced diabetes mellitus without complications"
* group[=].element[=].target[+].code = #014
* group[=].element[=].target[=].display = "Diabetes"
* group[=].element[=].target[=].equivalence = #equivalent

// 015 - Chronic liver disease
* group[=].element[+].code = #K70.30
* group[=].element[=].display = "Alcoholic cirrhosis of liver without ascites"
* group[=].element[=].target[+].code = #015
* group[=].element[=].target[=].display = "Chronic liver disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 015 - Chronic liver disease
* group[=].element[+].code = #K70.31
* group[=].element[=].display = "Alcoholic cirrhosis of liver with ascites"
* group[=].element[=].target[+].code = #015
* group[=].element[=].target[=].display = "Chronic liver disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 015 - Chronic liver disease
* group[=].element[+].code = #K73.9
* group[=].element[=].display = "Chronic hepatitis, unspecified"
* group[=].element[=].target[+].code = #015
* group[=].element[=].target[=].display = "Chronic liver disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 015 - Chronic liver disease
* group[=].element[+].code = #K74.0
* group[=].element[=].display = "Hepatic fibrosis"
* group[=].element[=].target[+].code = #015
* group[=].element[=].target[=].display = "Chronic liver disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 015 - Chronic liver disease
* group[=].element[+].code = #K74.60
* group[=].element[=].display = "Unspecified cirrhosis of liver"
* group[=].element[=].target[+].code = #015
* group[=].element[=].target[=].display = "Chronic liver disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 015 - Chronic liver disease
* group[=].element[+].code = #K74.69
* group[=].element[=].display = "Other cirrhosis of liver"
* group[=].element[=].target[+].code = #015
* group[=].element[=].target[=].display = "Chronic liver disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 015 - Chronic liver disease
* group[=].element[+].code = #K76.0
* group[=].element[=].display = "Fatty (change of) liver, not elsewhere classified"
* group[=].element[=].target[+].code = #015
* group[=].element[=].target[=].display = "Chronic liver disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 015 - Chronic liver disease
* group[=].element[+].code = #K76.9
* group[=].element[=].display = "Liver disease, unspecified"
* group[=].element[=].target[+].code = #015
* group[=].element[=].target[=].display = "Chronic liver disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 016 - Chronic heart disease
* group[=].element[+].code = #I25.10
* group[=].element[=].display = "Atherosclerotic heart disease of native coronary artery without angina pectoris"
* group[=].element[=].target[+].code = #016
* group[=].element[=].target[=].display = "Chronic heart disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 016 - Chronic heart disease
* group[=].element[+].code = #I25.9
* group[=].element[=].display = "Chronic ischemic heart disease, unspecified"
* group[=].element[=].target[+].code = #016
* group[=].element[=].target[=].display = "Chronic heart disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 016 - Chronic heart disease
* group[=].element[+].code = #I50.9
* group[=].element[=].display = "Heart failure, unspecified"
* group[=].element[=].target[+].code = #016
* group[=].element[=].target[=].display = "Chronic heart disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 016 - Chronic heart disease
* group[=].element[+].code = #I50.20
* group[=].element[=].display = "Unspecified systolic (congestive) heart failure"
* group[=].element[=].target[+].code = #016
* group[=].element[=].target[=].display = "Chronic heart disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 016 - Chronic heart disease
* group[=].element[+].code = #I50.30
* group[=].element[=].display = "Unspecified diastolic (congestive) heart failure"
* group[=].element[=].target[+].code = #016
* group[=].element[=].target[=].display = "Chronic heart disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 016 - Chronic heart disease
* group[=].element[+].code = #I42.9
* group[=].element[=].display = "Cardiomyopathy, unspecified"
* group[=].element[=].target[+].code = #016
* group[=].element[=].target[=].display = "Chronic heart disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 016 - Chronic heart disease
* group[=].element[+].code = #I42.0
* group[=].element[=].display = "Dilated cardiomyopathy"
* group[=].element[=].target[+].code = #016
* group[=].element[=].target[=].display = "Chronic heart disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 016 - Chronic heart disease
* group[=].element[+].code = #Q24.9
* group[=].element[=].display = "Congenital malformation of heart, unspecified"
* group[=].element[=].target[+].code = #016
* group[=].element[=].target[=].display = "Chronic heart disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 017 - Chronic lung disease
* group[=].element[+].code = #J44.9
* group[=].element[=].display = "Chronic obstructive pulmonary disease, unspecified"
* group[=].element[=].target[+].code = #017
* group[=].element[=].target[=].display = "Chronic lung disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 017 - Chronic lung disease
* group[=].element[+].code = #J44.1
* group[=].element[=].display = "Chronic obstructive pulmonary disease with (acute) exacerbation"
* group[=].element[=].target[+].code = #017
* group[=].element[=].target[=].display = "Chronic lung disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 017 - Chronic lung disease
* group[=].element[+].code = #J43.9
* group[=].element[=].display = "Emphysema, unspecified"
* group[=].element[=].target[+].code = #017
* group[=].element[=].target[=].display = "Chronic lung disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 017 - Chronic lung disease
* group[=].element[+].code = #J84.9
* group[=].element[=].display = "Interstitial pulmonary disease, unspecified"
* group[=].element[=].target[+].code = #017
* group[=].element[=].target[=].display = "Chronic lung disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 017 - Chronic lung disease
* group[=].element[+].code = #J84.10
* group[=].element[=].display = "Pulmonary fibrosis, unspecified"
* group[=].element[=].target[+].code = #017
* group[=].element[=].target[=].display = "Chronic lung disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 017 - Chronic lung disease
* group[=].element[+].code = #J47.9
* group[=].element[=].display = "Bronchiectasis, uncomplicated"
* group[=].element[=].target[+].code = #017
* group[=].element[=].target[=].display = "Chronic lung disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 017 - Chronic lung disease
* group[=].element[+].code = #P27.1
* group[=].element[=].display = "Bronchopulmonary dysplasia originating in the perinatal period"
* group[=].element[=].target[+].code = #017
* group[=].element[=].target[=].display = "Chronic lung disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 018 - Laboratory Evidence of Immunity or confirmation of Hepatitis A disease
* group[=].element[+].code = #D73.0
* group[=].element[=].display = "Hyposplenism"
* group[=].element[=].target[+].code = #018
* group[=].element[=].target[=].display = "Laboratory Evidence of Immunity or confirmation of Hepatitis A disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 018 - Laboratory Evidence of Immunity or confirmation of Hepatitis A disease
* group[=].element[+].code = #Q89.01
* group[=].element[=].display = "Asplenia (congenital)"
* group[=].element[=].target[+].code = #018
* group[=].element[=].target[=].display = "Laboratory Evidence of Immunity or confirmation of Hepatitis A disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 018 - Laboratory Evidence of Immunity or confirmation of Hepatitis A disease
* group[=].element[+].code = #D73.89
* group[=].element[=].display = "Other diseases of spleen"
* group[=].element[=].target[+].code = #018
* group[=].element[=].target[=].display = "Laboratory Evidence of Immunity or confirmation of Hepatitis A disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 018 - Laboratory Evidence of Immunity or confirmation of Hepatitis A disease
* group[=].element[+].code = #Z90.81
* group[=].element[=].display = "Acquired absence of spleen"
* group[=].element[=].target[+].code = #018
* group[=].element[=].target[=].display = "Laboratory Evidence of Immunity or confirmation of Hepatitis A disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 019 - Laboratory Evidence of Immunity or confirmation of Hepatitis B disease
* group[=].element[+].code = #N18.1
* group[=].element[=].display = "Chronic kidney disease, stage 1"
* group[=].element[=].target[+].code = #019
* group[=].element[=].target[=].display = "Laboratory Evidence of Immunity or confirmation of Hepatitis B disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 019 - Laboratory Evidence of Immunity or confirmation of Hepatitis B disease
* group[=].element[+].code = #N18.2
* group[=].element[=].display = "Chronic kidney disease, stage 2 (mild)"
* group[=].element[=].target[+].code = #019
* group[=].element[=].target[=].display = "Laboratory Evidence of Immunity or confirmation of Hepatitis B disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 019 - Laboratory Evidence of Immunity or confirmation of Hepatitis B disease
* group[=].element[+].code = #N18.30
* group[=].element[=].display = "Chronic kidney disease, stage 3 unspecified"
* group[=].element[=].target[+].code = #019
* group[=].element[=].target[=].display = "Laboratory Evidence of Immunity or confirmation of Hepatitis B disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 019 - Laboratory Evidence of Immunity or confirmation of Hepatitis B disease
* group[=].element[+].code = #N18.4
* group[=].element[=].display = "Chronic kidney disease, stage 4 (severe)"
* group[=].element[=].target[+].code = #019
* group[=].element[=].target[=].display = "Laboratory Evidence of Immunity or confirmation of Hepatitis B disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 019 - Laboratory Evidence of Immunity or confirmation of Hepatitis B disease
* group[=].element[+].code = #N18.5
* group[=].element[=].display = "Chronic kidney disease, stage 5"
* group[=].element[=].target[+].code = #019
* group[=].element[=].target[=].display = "Laboratory Evidence of Immunity or confirmation of Hepatitis B disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 019 - Laboratory Evidence of Immunity or confirmation of Hepatitis B disease
* group[=].element[+].code = #N18.6
* group[=].element[=].display = "End stage renal disease"
* group[=].element[=].target[+].code = #019
* group[=].element[=].target[=].display = "Laboratory Evidence of Immunity or confirmation of Hepatitis B disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 019 - Laboratory Evidence of Immunity or confirmation of Hepatitis B disease
* group[=].element[+].code = #N18.9
* group[=].element[=].display = "Chronic kidney disease, unspecified"
* group[=].element[=].target[+].code = #019
* group[=].element[=].target[=].display = "Laboratory Evidence of Immunity or confirmation of Hepatitis B disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 019 - Laboratory Evidence of Immunity or confirmation of Hepatitis B disease
* group[=].element[+].code = #Z99.2
* group[=].element[=].display = "Dependence on renal dialysis"
* group[=].element[=].target[+].code = #019
* group[=].element[=].target[=].display = "Laboratory Evidence of Immunity or confirmation of Hepatitis B disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 026 - Persons with perinatal HIV infection who do not have evidence of severe immunosuppression and who were vaccinated with MMR before establishment of antiviral therapy [ART]
* group[=].element[+].code = #B20
* group[=].element[=].display = "Human immunodeficiency virus [HIV] disease"
* group[=].element[=].target[+].code = #026
* group[=].element[=].target[=].display = "Persons with perinatal HIV infection who do not have evidence of severe immunosuppression and who were vaccinated with MMR before establishment of antiviral therapy [ART]"
* group[=].element[=].target[=].equivalence = #equivalent

// 026 - Persons with perinatal HIV infection who do not have evidence of severe immunosuppression and who were vaccinated with MMR before establishment of antiviral therapy [ART]
* group[=].element[+].code = #Z21
* group[=].element[=].display = "Asymptomatic human immunodeficiency virus [HIV] infection status"
* group[=].element[=].target[+].code = #026
* group[=].element[=].target[=].display = "Persons with perinatal HIV infection who do not have evidence of severe immunosuppression and who were vaccinated with MMR before establishment of antiviral therapy [ART]"
* group[=].element[=].target[=].equivalence = #equivalent

// 027 - Asthma
* group[=].element[+].code = #J45.20
* group[=].element[=].display = "Mild intermittent asthma, uncomplicated"
* group[=].element[=].target[+].code = #027
* group[=].element[=].target[=].display = "Asthma"
* group[=].element[=].target[=].equivalence = #equivalent

// 027 - Asthma
* group[=].element[+].code = #J45.30
* group[=].element[=].display = "Mild persistent asthma, uncomplicated"
* group[=].element[=].target[+].code = #027
* group[=].element[=].target[=].display = "Asthma"
* group[=].element[=].target[=].equivalence = #equivalent

// 027 - Asthma
* group[=].element[+].code = #J45.40
* group[=].element[=].display = "Moderate persistent asthma, uncomplicated"
* group[=].element[=].target[+].code = #027
* group[=].element[=].target[=].display = "Asthma"
* group[=].element[=].target[=].equivalence = #equivalent

// 027 - Asthma
* group[=].element[+].code = #J45.50
* group[=].element[=].display = "Severe persistent asthma, uncomplicated"
* group[=].element[=].target[+].code = #027
* group[=].element[=].target[=].display = "Asthma"
* group[=].element[=].target[=].equivalence = #equivalent

// 027 - Asthma
* group[=].element[+].code = #J45.909
* group[=].element[=].display = "Unspecified asthma, uncomplicated"
* group[=].element[=].target[+].code = #027
* group[=].element[=].target[=].display = "Asthma"
* group[=].element[=].target[=].equivalence = #equivalent

// 027 - Asthma
* group[=].element[+].code = #J45.998
* group[=].element[=].display = "Other asthma"
* group[=].element[=].target[+].code = #027
* group[=].element[=].target[=].display = "Asthma"
* group[=].element[=].target[=].equivalence = #equivalent

// 028 - Intussusception
* group[=].element[+].code = #K56.1
* group[=].element[=].display = "Intussusception"
* group[=].element[=].target[+].code = #028
* group[=].element[=].target[=].display = "Intussusception"
* group[=].element[=].target[=].equivalence = #equivalent

// 029 - Acute gastroenteritis
* group[=].element[+].code = #K52.9
* group[=].element[=].display = "Noninfective gastroenteritis and colitis, unspecified"
* group[=].element[=].target[+].code = #029
* group[=].element[=].target[=].display = "Acute gastroenteritis"
* group[=].element[=].target[=].equivalence = #equivalent

// 029 - Acute gastroenteritis
* group[=].element[+].code = #A09
* group[=].element[=].display = "Infectious gastroenteritis and colitis, unspecified"
* group[=].element[=].target[+].code = #029
* group[=].element[=].target[=].display = "Acute gastroenteritis"
* group[=].element[=].target[=].equivalence = #equivalent

// 029 - Acute gastroenteritis
* group[=].element[+].code = #A08.0
* group[=].element[=].display = "Rotaviral enteritis"
* group[=].element[=].target[+].code = #029
* group[=].element[=].target[=].display = "Acute gastroenteritis"
* group[=].element[=].target[=].equivalence = #equivalent

// 029 - Acute gastroenteritis
* group[=].element[+].code = #A08.39
* group[=].element[=].display = "Other viral enteritis"
* group[=].element[=].target[+].code = #029
* group[=].element[=].target[=].display = "Acute gastroenteritis"
* group[=].element[=].target[=].equivalence = #equivalent

// 030 - Acute febrile illness
* group[=].element[+].code = #R50.9
* group[=].element[=].display = "Fever, unspecified"
* group[=].element[=].target[+].code = #030
* group[=].element[=].target[=].display = "Acute febrile illness"
* group[=].element[=].target[=].equivalence = #equivalent

// 031 - Tuberculosis
* group[=].element[+].code = #A15.0
* group[=].element[=].display = "Tuberculosis of lung"
* group[=].element[=].target[+].code = #031
* group[=].element[=].target[=].display = "Tuberculosis"
* group[=].element[=].target[=].equivalence = #equivalent

// 031 - Tuberculosis
* group[=].element[+].code = #A15.9
* group[=].element[=].display = "Respiratory tuberculosis unspecified"
* group[=].element[=].target[+].code = #031
* group[=].element[=].target[=].display = "Tuberculosis"
* group[=].element[=].target[=].equivalence = #equivalent

// 031 - Tuberculosis
* group[=].element[+].code = #A18.89
* group[=].element[=].display = "Tuberculosis of other sites"
* group[=].element[=].target[+].code = #031
* group[=].element[=].target[=].display = "Tuberculosis"
* group[=].element[=].target[=].equivalence = #equivalent

// 031 - Tuberculosis
* group[=].element[+].code = #A19.9
* group[=].element[=].display = "Miliary tuberculosis, unspecified"
* group[=].element[=].target[+].code = #031
* group[=].element[=].target[=].display = "Tuberculosis"
* group[=].element[=].target[=].equivalence = #equivalent

// 031 - Tuberculosis
* group[=].element[+].code = #R76.11
* group[=].element[=].display = "Nonspecific reaction to tuberculin skin test without active tuberculosis"
* group[=].element[=].target[+].code = #031
* group[=].element[=].target[=].display = "Tuberculosis"
* group[=].element[=].target[=].equivalence = #equivalent

// 031 - Tuberculosis
* group[=].element[+].code = #Z86.11
* group[=].element[=].display = "Personal history of tuberculosis"
* group[=].element[=].target[+].code = #031
* group[=].element[=].target[=].display = "Tuberculosis"
* group[=].element[=].target[=].equivalence = #equivalent
// Z99.2 also cited by observation 032

// 034 - Receiving long-term aspirin therapy
* group[=].element[+].code = #Z79.82
* group[=].element[=].display = "Long term (current) use of aspirin"
* group[=].element[=].target[+].code = #034
* group[=].element[=].target[=].display = "Receiving long-term aspirin therapy"
* group[=].element[=].target[=].equivalence = #equivalent

// 039 - Receives treatment for STD
* group[=].element[+].code = #Z11.3
* group[=].element[=].display = "Encounter for screening for infections with a predominantly sexual mode of transmission"
* group[=].element[=].target[+].code = #039
* group[=].element[=].target[=].display = "Receives treatment for STD"
* group[=].element[=].target[=].equivalence = #equivalent

// 039 - Receives treatment for STD
* group[=].element[+].code = #Z11.4
* group[=].element[=].display = "Encounter for screening for human immunodeficiency virus [HIV]"
* group[=].element[=].target[+].code = #039
* group[=].element[=].target[=].display = "Receives treatment for STD"
* group[=].element[=].target[=].equivalence = #equivalent

// 039 - Receives treatment for STD
* group[=].element[+].code = #Z20.2
* group[=].element[=].display = "Contact with and (suspected) exposure to infections with a predominantly sexual mode of transmission"
* group[=].element[=].target[+].code = #039
* group[=].element[=].target[=].display = "Receives treatment for STD"
* group[=].element[=].target[=].equivalence = #equivalent

// 040 - Illicit drug use
* group[=].element[+].code = #F19.10
* group[=].element[=].display = "Other psychoactive substance abuse, uncomplicated"
* group[=].element[=].target[+].code = #040
* group[=].element[=].target[=].display = "Illicit drug use"
* group[=].element[=].target[=].equivalence = #equivalent

// 040 - Illicit drug use
* group[=].element[+].code = #F14.10
* group[=].element[=].display = "Cocaine abuse, uncomplicated"
* group[=].element[=].target[+].code = #040
* group[=].element[=].target[=].display = "Illicit drug use"
* group[=].element[=].target[=].equivalence = #equivalent

// 040 - Illicit drug use
* group[=].element[+].code = #F11.10
* group[=].element[=].display = "Opioid abuse, uncomplicated"
* group[=].element[=].target[+].code = #040
* group[=].element[=].target[=].display = "Illicit drug use"
* group[=].element[=].target[=].equivalence = #equivalent

// 040 - Illicit drug use
* group[=].element[+].code = #F16.10
* group[=].element[=].display = "Hallucinogen abuse, uncomplicated"
* group[=].element[=].target[+].code = #040
* group[=].element[=].target[=].display = "Illicit drug use"
* group[=].element[=].target[=].equivalence = #equivalent
// F11.10 also cited by observation 041
// F19.10 also cited by observation 041

// 042 - Smoke cigarettes
* group[=].element[+].code = #F17.210
* group[=].element[=].display = "Nicotine dependence, cigarettes, uncomplicated"
* group[=].element[=].target[+].code = #042
* group[=].element[=].target[=].display = "Smoke cigarettes"
* group[=].element[=].target[=].equivalence = #equivalent

// 042 - Smoke cigarettes
* group[=].element[+].code = #Z72.0
* group[=].element[=].display = "Tobacco use"
* group[=].element[=].target[+].code = #042
* group[=].element[=].target[=].display = "Smoke cigarettes"
* group[=].element[=].target[=].equivalence = #equivalent

// 043 - Alcoholism
* group[=].element[+].code = #F10.20
* group[=].element[=].display = "Alcohol dependence, uncomplicated"
* group[=].element[=].target[+].code = #043
* group[=].element[=].target[=].display = "Alcoholism"
* group[=].element[=].target[=].equivalence = #equivalent

// 043 - Alcoholism
* group[=].element[+].code = #F10.10
* group[=].element[=].display = "Alcohol abuse, uncomplicated"
* group[=].element[=].target[+].code = #043
* group[=].element[=].target[=].display = "Alcoholism"
* group[=].element[=].target[=].equivalence = #equivalent
// N18.6 also cited by observation 065
// N18.5 also cited by observation 065
// N18.9 also cited by observation 065

// 071 - Household contact with hepatitis B surface antigen-positive persons
* group[=].element[+].code = #Z11.59
* group[=].element[=].display = "Encounter for screening for other viral diseases"
* group[=].element[=].target[+].code = #071
* group[=].element[=].target[=].display = "Household contact with hepatitis B surface antigen-positive persons"
* group[=].element[=].target[=].equivalence = #equivalent

// 076 - Progressive neurologic disorder
* group[=].element[+].code = #G31.9
* group[=].element[=].display = "Degenerative disease of nervous system, unspecified"
* group[=].element[=].target[+].code = #076
* group[=].element[=].target[=].display = "Progressive neurologic disorder"
* group[=].element[=].target[=].equivalence = #equivalent

// 077 - Received inactivated or unknown measles vaccine between 1963-1967
* group[=].element[+].code = #T50.B95A
* group[=].element[=].display = "Adverse effect of other viral vaccines, initial encounter"
* group[=].element[=].target[+].code = #077
* group[=].element[=].target[=].display = "Received inactivated or unknown measles vaccine between 1963-1967"
* group[=].element[=].target[=].equivalence = #equivalent

// 077 - Received inactivated or unknown measles vaccine between 1963-1967
* group[=].element[+].code = #Z88.9
* group[=].element[=].display = "Allergy status to unspecified drugs, medicaments and biological substances"
* group[=].element[=].target[+].code = #077
* group[=].element[=].target[=].display = "Received inactivated or unknown measles vaccine between 1963-1967"
* group[=].element[=].target[=].equivalence = #equivalent
// T50.B95A also cited by observation 081

// 081 - Severe allergic reaction after previous dose of Polio
* group[=].element[+].code = #Z91.012
* group[=].element[=].display = "Allergy to eggs"
* group[=].element[=].target[+].code = #081
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Polio"
* group[=].element[=].target[=].equivalence = #equivalent
// T50.B95A also cited by observation 082
// T50.B95A also cited by observation 083
// T50.B95A also cited by observation 084
// T50.B95A also cited by observation 085

// 086 - Severe allergic reaction after previous dose of Pertussis
* group[=].element[+].code = #T50.A15A
* group[=].element[=].display = "Adverse effect of pertussis vaccine, including combinations with a pertussis component, initial encounter"
* group[=].element[=].target[+].code = #086
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Pertussis"
* group[=].element[=].target[=].equivalence = #equivalent
// T50.B95A also cited by observation 086

// 087 - Severe allergic reaction after previous dose of Diphtheria
* group[=].element[+].code = #T50.A95A
* group[=].element[=].display = "Adverse effect of other bacterial vaccines, initial encounter"
* group[=].element[=].target[+].code = #087
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Diphtheria"
* group[=].element[=].target[=].equivalence = #equivalent
// T50.B95A also cited by observation 087
// T50.A95A also cited by observation 088
// T50.B95A also cited by observation 088
// T50.B95A also cited by observation 089
// T50.B95A also cited by observation 090
// T50.B95A also cited by observation 091
// T50.B95A also cited by observation 092
// T50.B95A also cited by observation 093
// T50.B95A also cited by observation 094
// T50.B95A also cited by observation 095
// T50.B95A also cited by observation 096
// T50.B95A also cited by observation 097
// T50.B95A also cited by observation 098
// T50.B95A also cited by observation 099
// T50.B95A also cited by observation 100
// Z91.012 also cited by observation 101

// 101 - Allergic reaction to egg protein
* group[=].element[+].code = #T78.1
* group[=].element[=].display = "Other adverse food reactions, not elsewhere classified"
* group[=].element[=].target[+].code = #101
* group[=].element[=].target[=].display = "Allergic reaction to egg protein"
* group[=].element[=].target[=].equivalence = #equivalent
// T78.1 also cited by observation 102

// 102 - Severe allergic reaction to gelatin
* group[=].element[+].code = #Z91.018
* group[=].element[=].display = "Allergy to other foods"
* group[=].element[=].target[+].code = #102
* group[=].element[=].target[=].display = "Severe allergic reaction to gelatin"
* group[=].element[=].target[=].equivalence = #equivalent

// 103 - Severe allergic reaction to arginine
* group[=].element[+].code = #T78.40XA
* group[=].element[=].display = "Allergy, unspecified, initial encounter"
* group[=].element[=].target[+].code = #103
* group[=].element[=].target[=].display = "Severe allergic reaction to arginine"
* group[=].element[=].target[=].equivalence = #equivalent

// 104 - Allergic reaction to latex
* group[=].element[+].code = #Z91.040
* group[=].element[=].display = "Latex allergy status"
* group[=].element[=].target[+].code = #104
* group[=].element[=].target[=].display = "Allergic reaction to latex"
* group[=].element[=].target[=].equivalence = #equivalent
// T78.1 also cited by observation 105
// Z91.018 also cited by observation 105

// 106 - Severe allergic reaction to gentamicin
* group[=].element[+].code = #Z88.1
* group[=].element[=].display = "Allergy status to other antibiotic agents"
* group[=].element[=].target[+].code = #106
* group[=].element[=].target[=].display = "Severe allergic reaction to gentamicin"
* group[=].element[=].target[=].equivalence = #equivalent

// 106 - Severe allergic reaction to gentamicin
* group[=].element[+].code = #T36.5X5A
* group[=].element[=].display = "Adverse effect of aminoglycosides, initial encounter"
* group[=].element[=].target[+].code = #106
* group[=].element[=].target[=].display = "Severe allergic reaction to gentamicin"
* group[=].element[=].target[=].equivalence = #equivalent
// Z88.1 also cited by observation 107
// T36.5X5A also cited by observation 107
// Z88.1 also cited by observation 108
// T36.5X5A also cited by observation 108
// Z88.1 also cited by observation 109

// 109 - Severe allergic reaction to polymyxin B
* group[=].element[+].code = #T36.8X5A
* group[=].element[=].display = "Adverse effect of other systemic antibiotics, initial encounter"
* group[=].element[=].target[+].code = #109
* group[=].element[=].target[=].display = "Severe allergic reaction to polymyxin B"
* group[=].element[=].target[=].equivalence = #equivalent
// Z91.018 also cited by observation 110
// T78.1 also cited by observation 110

// 111 - Hypersensitivity to the preservative 2-phenoxyethanol
* group[=].element[+].code = #T78.49XA
* group[=].element[=].display = "Other allergy, initial encounter"
* group[=].element[=].target[+].code = #111
* group[=].element[=].target[=].display = "Hypersensitivity to the preservative 2-phenoxyethanol"
* group[=].element[=].target[=].equivalence = #equivalent
// N18.6 also cited by observation 113

// 115 - Severe allergic reaction to protamine sulfate
* group[=].element[+].code = #T45.7X5A
* group[=].element[=].display = "Adverse effect of anticoagulant antagonists, vitamin K and other coagulants, initial encounter"
* group[=].element[=].target[+].code = #115
* group[=].element[=].target[=].display = "Severe allergic reaction to protamine sulfate"
* group[=].element[=].target[=].equivalence = #equivalent

// 115 - Severe allergic reaction to protamine sulfate
* group[=].element[+].code = #Z88.8
* group[=].element[=].display = "Allergy status to other drugs, medicaments and biological substances"
* group[=].element[=].target[+].code = #115
* group[=].element[=].target[=].display = "Severe allergic reaction to protamine sulfate"
* group[=].element[=].target[=].equivalence = #equivalent
// T50.A95A also cited by observation 116
// Z88.8 also cited by observation 116
// T50.A95A also cited by observation 118
// Z88.8 also cited by observation 118

// 121 - Homelessness
* group[=].element[+].code = #Z59.00
* group[=].element[=].display = "Homelessness unspecified"
* group[=].element[=].target[+].code = #121
* group[=].element[=].target[=].display = "Homelessness"
* group[=].element[=].target[=].equivalence = #equivalent
// Z91.018 also cited by observation 122
// T50.B95A also cited by observation 122
// B20 also cited by observation 142
// Z21 also cited by observation 142

// 142 - Travel to or working in countries that have high or intermediate endemicity of Hepatitis A
* group[=].element[+].code = #D84.821
* group[=].element[=].display = "Immunodeficiency due to drugs"
* group[=].element[=].target[+].code = #142
* group[=].element[=].target[=].display = "Travel to or working in countries that have high or intermediate endemicity of Hepatitis A"
* group[=].element[=].target[=].equivalence = #equivalent
// D84.9 also cited by observation 142
// B20 also cited by observation 155
// Z21 also cited by observation 155

// 156 - Generalized malignant neoplasm
* group[=].element[+].code = #C80.0
* group[=].element[=].display = "Disseminated malignant neoplasm, unspecified"
* group[=].element[=].target[+].code = #156
* group[=].element[=].target[=].display = "Generalized malignant neoplasm"
* group[=].element[=].target[=].equivalence = #equivalent

// 156 - Generalized malignant neoplasm
* group[=].element[+].code = #C80.1
* group[=].element[=].display = "Malignant (primary) neoplasm, unspecified"
* group[=].element[=].target[+].code = #156
* group[=].element[=].target[=].display = "Generalized malignant neoplasm"
* group[=].element[=].target[=].equivalence = #equivalent

// 157 - Solid organ transplantation
* group[=].element[+].code = #Z94.0
* group[=].element[=].display = "Kidney transplant status"
* group[=].element[=].target[+].code = #157
* group[=].element[=].target[=].display = "Solid organ transplantation"
* group[=].element[=].target[=].equivalence = #equivalent

// 157 - Solid organ transplantation
* group[=].element[+].code = #Z94.1
* group[=].element[=].display = "Heart transplant status"
* group[=].element[=].target[+].code = #157
* group[=].element[=].target[=].display = "Solid organ transplantation"
* group[=].element[=].target[=].equivalence = #equivalent

// 157 - Solid organ transplantation
* group[=].element[+].code = #Z94.2
* group[=].element[=].display = "Lung transplant status"
* group[=].element[=].target[+].code = #157
* group[=].element[=].target[=].display = "Solid organ transplantation"
* group[=].element[=].target[=].equivalence = #equivalent

// 157 - Solid organ transplantation
* group[=].element[+].code = #Z94.4
* group[=].element[=].display = "Liver transplant status"
* group[=].element[=].target[+].code = #157
* group[=].element[=].target[=].display = "Solid organ transplantation"
* group[=].element[=].target[=].equivalence = #equivalent

// 157 - Solid organ transplantation
* group[=].element[+].code = #Z94.9
* group[=].element[=].display = "Transplanted organ and tissue status, unspecified"
* group[=].element[=].target[+].code = #157
* group[=].element[=].target[=].display = "Solid organ transplantation"
* group[=].element[=].target[=].equivalence = #equivalent

// 158 - Immunosuppressive therapy
* group[=].element[+].code = #Z79.52
* group[=].element[=].display = "Long term (current) use of systemic steroids"
* group[=].element[=].target[+].code = #158
* group[=].element[=].target[=].display = "Immunosuppressive therapy"
* group[=].element[=].target[=].equivalence = #equivalent

// 158 - Immunosuppressive therapy
* group[=].element[+].code = #Z79.899
* group[=].element[=].display = "Other long term (current) drug therapy"
* group[=].element[=].target[+].code = #158
* group[=].element[=].target[=].display = "Immunosuppressive therapy"
* group[=].element[=].target[=].equivalence = #equivalent
// D84.821 also cited by observation 158

// 159 - Radiation therapy
* group[=].element[+].code = #Z51.0
* group[=].element[=].display = "Encounter for antineoplastic radiation therapy"
* group[=].element[=].target[+].code = #159
* group[=].element[=].target[=].display = "Radiation therapy"
* group[=].element[=].target[=].equivalence = #equivalent
// D73.0 also cited by observation 160
// Q89.01 also cited by observation 160
// Z90.81 also cited by observation 160
// N18.1 also cited by observation 161
// N18.2 also cited by observation 161

// 161 - Chronic kidney disease
* group[=].element[+].code = #N18.3
* group[=].element[=].display = "Chronic kidney disease, stage 3 (moderate)"
* group[=].element[=].target[+].code = #161
* group[=].element[=].target[=].display = "Chronic kidney disease"
* group[=].element[=].target[=].equivalence = #equivalent
// N18.4 also cited by observation 161
// N18.5 also cited by observation 161
// N18.9 also cited by observation 161

// 162 - Travel to areas at risk for Yellow Fever transmission
* group[=].element[+].code = #N04.9
* group[=].element[=].display = "Nephrotic syndrome with unspecified morphologic changes"
* group[=].element[=].target[+].code = #162
* group[=].element[=].target[=].display = "Travel to areas at risk for Yellow Fever transmission"
* group[=].element[=].target[=].equivalence = #equivalent

// 168 - Chemotherapy
* group[=].element[+].code = #Z51.11
* group[=].element[=].display = "Encounter for antineoplastic chemotherapy"
* group[=].element[=].target[+].code = #168
* group[=].element[=].target[=].display = "Chemotherapy"
* group[=].element[=].target[=].equivalence = #equivalent

// 168 - Chemotherapy
* group[=].element[+].code = #Z51.12
* group[=].element[=].display = "Encounter for antineoplastic immunotherapy"
* group[=].element[=].target[+].code = #168
* group[=].element[=].target[=].display = "Chemotherapy"
* group[=].element[=].target[=].equivalence = #equivalent

// 169 - History of sexual abuse or assault
* group[=].element[+].code = #Z04.81
* group[=].element[=].display = "Encounter for examination and observation of victim following forced sexual exploitation"
* group[=].element[=].target[+].code = #169
* group[=].element[=].target[=].display = "History of sexual abuse or assault"
* group[=].element[=].target[=].equivalence = #equivalent

// 169 - History of sexual abuse or assault
* group[=].element[+].code = #T74.21XA
* group[=].element[=].display = "Adult sexual abuse, confirmed, initial encounter"
* group[=].element[=].target[+].code = #169
* group[=].element[=].target[=].display = "History of sexual abuse or assault"
* group[=].element[=].target[=].equivalence = #equivalent

// 169 - History of sexual abuse or assault
* group[=].element[+].code = #T74.22XA
* group[=].element[=].display = "Child sexual abuse, confirmed, initial encounter"
* group[=].element[=].target[+].code = #169
* group[=].element[=].target[=].display = "History of sexual abuse or assault"
* group[=].element[=].target[=].equivalence = #equivalent
// Z33.1 also cited by observation 170

// 170 - Onset of pregnancy
* group[=].element[+].code = #Z34.90
* group[=].element[=].display = "Encounter for supervision of normal pregnancy, unspecified, unspecified trimester"
* group[=].element[=].target[+].code = #170
* group[=].element[=].target[=].display = "Onset of pregnancy"
* group[=].element[=].target[=].equivalence = #equivalent

// 178 - Leukemia
* group[=].element[+].code = #C95.90
* group[=].element[=].display = "Leukemia, unspecified not having achieved remission"
* group[=].element[=].target[+].code = #178
* group[=].element[=].target[=].display = "Leukemia"
* group[=].element[=].target[=].equivalence = #equivalent

// 178 - Leukemia
* group[=].element[+].code = #C91.00
* group[=].element[=].display = "Acute lymphoblastic leukemia not having achieved remission"
* group[=].element[=].target[+].code = #178
* group[=].element[=].target[=].display = "Leukemia"
* group[=].element[=].target[=].equivalence = #equivalent

// 178 - Leukemia
* group[=].element[+].code = #C92.00
* group[=].element[=].display = "Acute myeloblastic leukemia, not having achieved remission"
* group[=].element[=].target[+].code = #178
* group[=].element[=].target[=].display = "Leukemia"
* group[=].element[=].target[=].equivalence = #equivalent

// 179 - Lymphoma
* group[=].element[+].code = #C85.90
* group[=].element[=].display = "Non-Hodgkin lymphoma, unspecified, unspecified site"
* group[=].element[=].target[+].code = #179
* group[=].element[=].target[=].display = "Lymphoma"
* group[=].element[=].target[=].equivalence = #equivalent

// 179 - Lymphoma
* group[=].element[+].code = #C84.40
* group[=].element[=].display = "Peripheral T-cell lymphoma, not elsewhere classified, unspecified site"
* group[=].element[=].target[+].code = #179
* group[=].element[=].target[=].display = "Lymphoma"
* group[=].element[=].target[=].equivalence = #equivalent

// 180 - Hodgkin's disease
* group[=].element[+].code = #C81.90
* group[=].element[=].display = "Hodgkin lymphoma, unspecified, unspecified site"
* group[=].element[=].target[+].code = #180
* group[=].element[=].target[=].display = "Hodgkin's disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 181 - Multiple myeloma
* group[=].element[+].code = #C90.00
* group[=].element[=].display = "Multiple myeloma not having achieved remission"
* group[=].element[=].target[+].code = #181
* group[=].element[=].target[=].display = "Multiple myeloma"
* group[=].element[=].target[=].equivalence = #equivalent
// B20 also cited by observation 183
// Z21 also cited by observation 183
// Z88.8 also cited by observation 187
// T78.49XA also cited by observation 187
// Z88.8 also cited by observation 188
// T78.49XA also cited by observation 188
// Z51.11 also cited by observation 189
// C80.1 also cited by observation 189
// Z51.11 also cited by observation 190

// 190 - Active treatment for hematologic malignancies
* group[=].element[+].code = #C96.9
* group[=].element[=].display = "Malignant neoplasm of lymphoid, hematopoietic and related tissue, unspecified"
* group[=].element[=].target[+].code = #190
* group[=].element[=].target[=].display = "Active treatment for hematologic malignancies"
* group[=].element[=].target[=].equivalence = #equivalent
// Z94.84 also cited by observation 191

// 192 - Severe allergic reaction after previous dose of any egg-based IIV or LAIV influenza vaccine
* group[=].element[+].code = #Z59.3
* group[=].element[=].display = "Problems related to living in residential institution"
* group[=].element[=].target[+].code = #192
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of any egg-based IIV or LAIV influenza vaccine"
* group[=].element[=].target[=].equivalence = #equivalent
// C80.1 also cited by observation 198
// J84.9 also cited by observation 199
// J84.10 also cited by observation 199

// 199 - Interstitial lung disease
* group[=].element[+].code = #J84.89
* group[=].element[=].display = "Other specified interstitial pulmonary diseases"
* group[=].element[=].target[+].code = #199
* group[=].element[=].target[=].display = "Interstitial lung disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 200 - Cystic fibrosis
* group[=].element[+].code = #E84.0
* group[=].element[=].display = "Cystic fibrosis with pulmonary manifestations"
* group[=].element[=].target[+].code = #200
* group[=].element[=].target[=].display = "Cystic fibrosis"
* group[=].element[=].target[=].equivalence = #equivalent

// 200 - Cystic fibrosis
* group[=].element[+].code = #E84.9
* group[=].element[=].display = "Cystic fibrosis, unspecified"
* group[=].element[=].target[+].code = #200
* group[=].element[=].target[=].display = "Cystic fibrosis"
* group[=].element[=].target[=].equivalence = #equivalent

// 201 - Pulmonary hypertension
* group[=].element[+].code = #I27.0
* group[=].element[=].display = "Primary pulmonary hypertension"
* group[=].element[=].target[+].code = #201
* group[=].element[=].target[=].display = "Pulmonary hypertension"
* group[=].element[=].target[=].equivalence = #equivalent

// 201 - Pulmonary hypertension
* group[=].element[+].code = #I27.20
* group[=].element[=].display = "Pulmonary hypertension, unspecified"
* group[=].element[=].target[+].code = #201
* group[=].element[=].target[=].display = "Pulmonary hypertension"
* group[=].element[=].target[=].equivalence = #equivalent

// 201 - Pulmonary hypertension
* group[=].element[+].code = #I27.9
* group[=].element[=].display = "Pulmonary heart disease, unspecified"
* group[=].element[=].target[+].code = #201
* group[=].element[=].target[=].display = "Pulmonary hypertension"
* group[=].element[=].target[=].equivalence = #equivalent

// 202 - Dementia
* group[=].element[+].code = #F03.90
* group[=].element[=].display = "Unspecified dementia, unspecified severity, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety"
* group[=].element[=].target[+].code = #202
* group[=].element[=].target[=].display = "Dementia"
* group[=].element[=].target[=].equivalence = #equivalent

// 202 - Dementia
* group[=].element[+].code = #G30.9
* group[=].element[=].display = "Alzheimer's disease, unspecified"
* group[=].element[=].target[+].code = #202
* group[=].element[=].target[=].display = "Dementia"
* group[=].element[=].target[=].equivalence = #equivalent

// 203 - Down syndrome
* group[=].element[+].code = #Q90.9
* group[=].element[=].display = "Down syndrome, unspecified"
* group[=].element[=].target[+].code = #203
* group[=].element[=].target[=].display = "Down syndrome"
* group[=].element[=].target[=].equivalence = #equivalent

// 204 - Obesity
* group[=].element[+].code = #E66.9
* group[=].element[=].display = "Obesity, unspecified"
* group[=].element[=].target[+].code = #204
* group[=].element[=].target[=].display = "Obesity"
* group[=].element[=].target[=].equivalence = #equivalent

// 204 - Obesity
* group[=].element[+].code = #E66.01
* group[=].element[=].display = "Morbid (severe) obesity due to excess calories"
* group[=].element[=].target[+].code = #204
* group[=].element[=].target[=].display = "Obesity"
* group[=].element[=].target[=].equivalence = #equivalent

// 205 - Thalassemia
* group[=].element[+].code = #D56.9
* group[=].element[=].display = "Thalassemia, unspecified"
* group[=].element[=].target[+].code = #205
* group[=].element[=].target[=].display = "Thalassemia"
* group[=].element[=].target[=].equivalence = #equivalent

// 205 - Thalassemia
* group[=].element[+].code = #D56.0
* group[=].element[=].display = "Alpha thalassemia"
* group[=].element[=].target[+].code = #205
* group[=].element[=].target[=].display = "Thalassemia"
* group[=].element[=].target[=].equivalence = #equivalent

// 205 - Thalassemia
* group[=].element[+].code = #D56.1
* group[=].element[=].display = "Beta thalassemia"
* group[=].element[=].target[+].code = #205
* group[=].element[=].target[=].display = "Thalassemia"
* group[=].element[=].target[=].equivalence = #equivalent

// 206 - Cerebrovascular disease
* group[=].element[+].code = #I67.9
* group[=].element[=].display = "Cerebrovascular disease, unspecified"
* group[=].element[=].target[+].code = #206
* group[=].element[=].target[=].display = "Cerebrovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 206 - Cerebrovascular disease
* group[=].element[+].code = #I63.9
* group[=].element[=].display = "Cerebral infarction, unspecified"
* group[=].element[=].target[+].code = #206
* group[=].element[=].target[=].display = "Cerebrovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 207 - Substance use disorder
* group[=].element[+].code = #F19.20
* group[=].element[=].display = "Other psychoactive substance dependence, uncomplicated"
* group[=].element[=].target[+].code = #207
* group[=].element[=].target[=].display = "Substance use disorder"
* group[=].element[=].target[=].equivalence = #equivalent
// F19.10 also cited by observation 207

// 208 - Mental Health conditions
* group[=].element[+].code = #F99
* group[=].element[=].display = "Mental disorder, not otherwise specified"
* group[=].element[=].target[+].code = #208
* group[=].element[=].target[=].display = "Mental Health conditions"
* group[=].element[=].target[=].equivalence = #equivalent
// J44.1 also cited by observation 209
// J44.9 also cited by observation 209
// J43.9 also cited by observation 215
// D84.821 also cited by observation 216
// D89.9 also cited by observation 216

// 223 - Severe allergic reaction after previous dose of orthopoxvirus vaccine
* group[=].element[+].code = #L20.9
* group[=].element[=].display = "Atopic dermatitis, unspecified"
* group[=].element[=].target[+].code = #223
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of orthopoxvirus vaccine"
* group[=].element[=].target[=].equivalence = #equivalent

// 223 - Severe allergic reaction after previous dose of orthopoxvirus vaccine
* group[=].element[+].code = #L20.89
* group[=].element[=].display = "Other atopic dermatitis"
* group[=].element[=].target[+].code = #223
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of orthopoxvirus vaccine"
* group[=].element[=].target[=].equivalence = #equivalent

// 225 - Household contact with history or presence of atopic dermatitis
* group[=].element[+].code = #L26
* group[=].element[=].display = "Exfoliative dermatitis"
* group[=].element[=].target[+].code = #225
* group[=].element[=].target[=].display = "Household contact with history or presence of atopic dermatitis"
* group[=].element[=].target[=].equivalence = #equivalent

// 225 - Household contact with history or presence of atopic dermatitis
* group[=].element[+].code = #L10.9
* group[=].element[=].display = "Pemphigus, unspecified"
* group[=].element[=].target[+].code = #225
* group[=].element[=].target[=].display = "Household contact with history or presence of atopic dermatitis"
* group[=].element[=].target[=].equivalence = #equivalent

// 240 - Healthcare personnel who care for patients infected with less virulent orthopoxviruses (e.g., Vaccinia virus or Cowpox virus)
* group[=].element[+].code = #Z20.828
* group[=].element[=].display = "Contact with and (suspected) exposure to other viral communicable diseases"
* group[=].element[=].target[+].code = #240
* group[=].element[=].target[=].display = "Healthcare personnel who care for patients infected with less virulent orthopoxviruses (e.g., Vaccinia virus or Cowpox virus)"
* group[=].element[=].target[=].equivalence = #equivalent
// Z20.828 also cited by observation 242
// D84.9 also cited by observation 246
// D84.821 also cited by observation 246
// D83.9 also cited by observation 246
// J45.40 also cited by observation 247
// J45.50 also cited by observation 247
// I25.10 also cited by observation 254

// 254 - Chronic cardiovascular disease
* group[=].element[+].code = #I51.9
* group[=].element[=].display = "Heart disease, unspecified"
* group[=].element[=].target[+].code = #254
* group[=].element[=].target[=].display = "Chronic cardiovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent
// I42.9 also cited by observation 254
// E66.01 also cited by observation 256

// 256 - Diabetes mellitus complicated by chronic kidney disease
* group[=].element[+].code = #E66.2
* group[=].element[=].display = "Morbid (severe) obesity with alveolar hypoventilation"
* group[=].element[=].target[+].code = #256
* group[=].element[=].target[=].display = "Diabetes mellitus complicated by chronic kidney disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 258 - Chronic hematologic disorders
* group[=].element[+].code = #D75.9
* group[=].element[=].display = "Disease of blood and blood-forming organs, unspecified"
* group[=].element[=].target[+].code = #258
* group[=].element[=].target[=].display = "Chronic hematologic disorders"
* group[=].element[=].target[=].equivalence = #equivalent

// 259 - Sickle cell disease
* group[=].element[+].code = #D57.1
* group[=].element[=].display = "Sickle-cell disease without crisis"
* group[=].element[=].target[+].code = #259
* group[=].element[=].target[=].display = "Sickle cell disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 259 - Sickle cell disease
* group[=].element[+].code = #D57.00
* group[=].element[=].display = "Hb-SS disease with crisis, unspecified"
* group[=].element[=].target[+].code = #259
* group[=].element[=].target[=].display = "Sickle cell disease"
* group[=].element[=].target[=].equivalence = #equivalent
// Z59.3 also cited by observation 260

// 262 - Frailty
* group[=].element[+].code = #R54
* group[=].element[=].display = "Age-related physical debility"
* group[=].element[=].target[+].code = #262
* group[=].element[=].target[=].display = "Frailty"
* group[=].element[=].target[=].equivalence = #equivalent

// 263 - Diabetes mellitus complicated by neuropathy
* group[=].element[+].code = #E11.40
* group[=].element[=].display = "Type 2 diabetes mellitus with diabetic neuropathy, unspecified"
* group[=].element[=].target[+].code = #263
* group[=].element[=].target[=].display = "Diabetes mellitus complicated by neuropathy"
* group[=].element[=].target[=].equivalence = #equivalent

// 263 - Diabetes mellitus complicated by neuropathy
* group[=].element[+].code = #E10.40
* group[=].element[=].display = "Type 1 diabetes mellitus with diabetic neuropathy, unspecified"
* group[=].element[=].target[+].code = #263
* group[=].element[=].target[=].display = "Diabetes mellitus complicated by neuropathy"
* group[=].element[=].target[=].equivalence = #equivalent

// 263 - Diabetes mellitus complicated by neuropathy
* group[=].element[+].code = #E13.40
* group[=].element[=].display = "Other specified diabetes mellitus with diabetic neuropathy, unspecified"
* group[=].element[=].target[+].code = #263
* group[=].element[=].target[=].display = "Diabetes mellitus complicated by neuropathy"
* group[=].element[=].target[=].equivalence = #equivalent

// 264 - Diabetes mellitus complicated by retinopathy
* group[=].element[+].code = #E11.319
* group[=].element[=].display = "Type 2 diabetes mellitus with unspecified diabetic retinopathy without macular edema"
* group[=].element[=].target[+].code = #264
* group[=].element[=].target[=].display = "Diabetes mellitus complicated by retinopathy"
* group[=].element[=].target[=].equivalence = #equivalent

// 264 - Diabetes mellitus complicated by retinopathy
* group[=].element[+].code = #E10.319
* group[=].element[=].display = "Type 1 diabetes mellitus with unspecified diabetic retinopathy without macular edema"
* group[=].element[=].target[+].code = #264
* group[=].element[=].target[=].display = "Diabetes mellitus complicated by retinopathy"
* group[=].element[=].target[=].equivalence = #equivalent
// E11.65 also cited by observation 265

// 265 - Diabetes mellitus complicated by end-organ damage
* group[=].element[+].code = #E11.69
* group[=].element[=].display = "Type 2 diabetes mellitus with other specified complication"
* group[=].element[=].target[+].code = #265
* group[=].element[=].target[=].display = "Diabetes mellitus complicated by end-organ damage"
* group[=].element[=].target[=].equivalence = #equivalent

// 265 - Diabetes mellitus complicated by end-organ damage
* group[=].element[+].code = #E10.69
* group[=].element[=].display = "Type 1 diabetes mellitus with other specified complication"
* group[=].element[=].target[+].code = #265
* group[=].element[=].target[=].display = "Diabetes mellitus complicated by end-organ damage"
* group[=].element[=].target[=].equivalence = #equivalent

// 265 - Diabetes mellitus complicated by end-organ damage
* group[=].element[+].code = #E13.69
* group[=].element[=].display = "Other specified diabetes mellitus with other specified complication"
* group[=].element[=].target[+].code = #265
* group[=].element[=].target[=].display = "Diabetes mellitus complicated by end-organ damage"
* group[=].element[=].target[=].equivalence = #equivalent

// 266 - Diabetes requiring treatment with insulin
* group[=].element[+].code = #Z79.4
* group[=].element[=].display = "Long term (current) use of insulin"
* group[=].element[=].target[+].code = #266
* group[=].element[=].target[=].display = "Diabetes requiring treatment with insulin"
* group[=].element[=].target[=].equivalence = #equivalent
// E10.9 also cited by observation 266
// E11.9 also cited by observation 266

// 267 - Diabetes requiring treatment with sodium-glucose cotransporter-2 (SGLT2) inhibitor
* group[=].element[+].code = #Z94.83
* group[=].element[=].display = "Pancreas transplant status"
* group[=].element[=].target[+].code = #267
* group[=].element[=].target[=].display = "Diabetes requiring treatment with sodium-glucose cotransporter-2 (SGLT2) inhibitor"
* group[=].element[=].target[=].equivalence = #equivalent
// Z94.9 also cited by observation 269
// D80.9 also cited by observation 270

// 270 - Severe allergic reaction after previous dose of Chikungunya vaccine
* group[=].element[+].code = #D80.1
* group[=].element[=].display = "Nonfamilial hypogammaglobulinemia"
* group[=].element[=].target[+].code = #270
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Chikungunya vaccine"
* group[=].element[=].target[=].equivalence = #equivalent

// 270 - Severe allergic reaction after previous dose of Chikungunya vaccine
* group[=].element[+].code = #D80.0
* group[=].element[=].display = "Hereditary hypogammaglobulinemia"
* group[=].element[=].target[+].code = #270
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Chikungunya vaccine"
* group[=].element[=].target[=].equivalence = #equivalent

// 274 - Early component complement inhibitor use
* group[=].element[+].code = #D84.1
* group[=].element[=].display = "Defects in the complement system"
* group[=].element[=].target[+].code = #274
* group[=].element[=].target[=].display = "Early component complement inhibitor use"
* group[=].element[=].target[=].equivalence = #equivalent
// Z79.899 also cited by observation 274

// 277 - Laboratory worker with potential for exposure to chikungunya virus
* group[=].element[+].code = #D58.2
* group[=].element[=].display = "Other hemoglobinopathies"
* group[=].element[=].target[+].code = #277
* group[=].element[=].target[=].display = "Laboratory worker with potential for exposure to chikungunya virus"
* group[=].element[=].target[=].equivalence = #equivalent
// D56.9 also cited by observation 277

// 277 - Laboratory worker with potential for exposure to chikungunya virus
* group[=].element[+].code = #D57.3
* group[=].element[=].display = "Sickle-cell trait"
* group[=].element[=].target[+].code = #277
* group[=].element[=].target[=].display = "Laboratory worker with potential for exposure to chikungunya virus"
* group[=].element[=].target[=].equivalence = #equivalent
