// GENERATED by cicada_generator/tool/generate_concept_maps.py from
// ScheduleSupportingData.xml — do not edit by hand.
//
// Every element here is a <codedValue> CDC publishes against an observation.
// The hand-written version carried 11 of them.
Instance: SnomedToCdsiObservation
InstanceOf: ConceptMap
Usage: #definition
Title: "SNOMED CT to CDSi Observation Code Map"
Description: "Maps SNOMED CT codes to CDSi observation codes used in immunization decision support. Generated from CDC's supporting data."
* status = #active
* experimental = false
// ValueSets, not CodeSystems: R4 binds ConceptMap.source[x] to a ValueSet.
* sourceCanonical = "http://fhirfli.dev/fhir/ig/cicada/ValueSet/vaccine-condition-codes-snomed"
* targetCanonical = "http://fhirfli.dev/fhir/ig/cicada/ValueSet/cdsi-observation-codes-vs"

* group[+].source = "http://snomed.info/sct"
* group[=].target = "http://fhirfli.dev/fhir/ig/cicada/CodeSystem/cdsi-observation-codes"

// 003 - Immunocompromised
* group[=].element[+].code = #370388006
* group[=].element[=].display = "Patient Immunocompromised"
* group[=].element[=].target[+].code = #003
* group[=].element[=].target[=].display = "Immunocompromised"
* group[=].element[=].target[=].equivalence = #equivalent

// 004 - Recipient of a hematopoietic stem cell transplant
* group[=].element[+].code = #234336002
* group[=].element[=].display = "Hemopoietic stem cell transplant [procedure]"
* group[=].element[=].target[+].code = #004
* group[=].element[=].target[=].display = "Recipient of a hematopoietic stem cell transplant"
* group[=].element[=].target[=].equivalence = #equivalent

// 004 - Recipient of a hematopoietic stem cell transplant
* group[=].element[+].code = #23719005
* group[=].element[=].display = "Transplantation of bone marrow [procedure]"
* group[=].element[=].target[+].code = #004
* group[=].element[=].target[=].display = "Recipient of a hematopoietic stem cell transplant"
* group[=].element[=].target[=].equivalence = #equivalent

// 005 - Hepatitis C virus infection
* group[=].element[+].code = #50711007
* group[=].element[=].display = "Viral hepatitis type C [disorder]"
* group[=].element[=].target[+].code = #005
* group[=].element[=].target[=].display = "Hepatitis C virus infection"
* group[=].element[=].target[=].equivalence = #equivalent

// 007 - Pregnant
* group[=].element[+].code = #77386006
* group[=].element[=].display = "Patient currently pregnant [finding]"
* group[=].element[=].target[+].code = #007
* group[=].element[=].target[=].display = "Pregnant"
* group[=].element[=].target[=].equivalence = #equivalent

// 007 - Pregnant
* group[=].element[+].code = #102874004
* group[=].element[=].display = "Possible pregnancy [finding]"
* group[=].element[=].target[+].code = #007
* group[=].element[=].target[=].display = "Pregnant"
* group[=].element[=].target[=].equivalence = #equivalent

// 007 - Pregnant
* group[=].element[+].code = #255409004
* group[=].element[=].display = "Pregnant woman [person]"
* group[=].element[=].target[+].code = #007
* group[=].element[=].target[=].display = "Pregnant"
* group[=].element[=].target[=].equivalence = #equivalent

// 009 - Breastfeeding
* group[=].element[+].code = #413712001
* group[=].element[=].display = "Breastfeeding [mother] [observable entity]"
* group[=].element[=].target[+].code = #009
* group[=].element[=].target[=].display = "Breastfeeding"
* group[=].element[=].target[=].equivalence = #equivalent

// 010 - Cerebrospinal fluid leaks
* group[=].element[+].code = #230744007
* group[=].element[=].display = "Cerebrospinal fluid leak [disorder]"
* group[=].element[=].target[+].code = #010
* group[=].element[=].target[=].display = "Cerebrospinal fluid leaks"
* group[=].element[=].target[=].equivalence = #equivalent

// 011 - Cochlear implants
* group[=].element[+].code = #449840001
* group[=].element[=].display = "Cochlear prosthesis in situ [finding]"
* group[=].element[=].target[+].code = #011
* group[=].element[=].target[=].display = "Cochlear implants"
* group[=].element[=].target[=].equivalence = #equivalent

// 011 - Cochlear implants
* group[=].element[+].code = #43252007
* group[=].element[=].display = "Cochlear prosthesis, device [physical object]"
* group[=].element[=].target[+].code = #011
* group[=].element[=].target[=].display = "Cochlear implants"
* group[=].element[=].target[=].equivalence = #equivalent

// 011 - Cochlear implants
* group[=].element[+].code = #359612003
* group[=].element[=].display = "Implantation of cochlear prosthetic device [procedure]"
* group[=].element[=].target[+].code = #011
* group[=].element[=].target[=].display = "Cochlear implants"
* group[=].element[=].target[=].equivalence = #equivalent

// 013 - Severe Combined Immunodeficiency [SCID]
* group[=].element[+].code = #31323000
* group[=].element[=].display = "Severe combined immunodeficiency disease [disorder]"
* group[=].element[=].target[+].code = #013
* group[=].element[=].target[=].display = "Severe Combined Immunodeficiency [SCID]"
* group[=].element[=].target[=].equivalence = #equivalent

// 014 - Diabetes
* group[=].element[+].code = #73211009
* group[=].element[=].display = "Diabetes mellitus [disorder]"
* group[=].element[=].target[+].code = #014
* group[=].element[=].target[=].display = "Diabetes"
* group[=].element[=].target[=].equivalence = #equivalent

// 015 - Chronic liver disease
* group[=].element[+].code = #328383001
* group[=].element[=].display = "Chronic liver disease [disorder]"
* group[=].element[=].target[+].code = #015
* group[=].element[=].target[=].display = "Chronic liver disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 015 - Chronic liver disease
* group[=].element[+].code = #19943007
* group[=].element[=].display = "Cirrhosis of liver [disorder]"
* group[=].element[=].target[+].code = #015
* group[=].element[=].target[=].display = "Chronic liver disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 016 - Chronic heart disease
* group[=].element[+].code = #128238001
* group[=].element[=].display = "Chronic heart disease [disorder]"
* group[=].element[=].target[+].code = #016
* group[=].element[=].target[=].display = "Chronic heart disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 016 - Chronic heart disease
* group[=].element[+].code = #42343007
* group[=].element[=].display = "Congestive heart failure [disorder]"
* group[=].element[=].target[+].code = #016
* group[=].element[=].target[=].display = "Chronic heart disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 016 - Chronic heart disease
* group[=].element[+].code = #57809008
* group[=].element[=].display = "Myocardial disease [disorder]"
* group[=].element[=].target[+].code = #016
* group[=].element[=].target[=].display = "Chronic heart disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 016 - Chronic heart disease
* group[=].element[+].code = #12770006
* group[=].element[=].display = "Cyanotic congenital heart disease [disorder]"
* group[=].element[=].target[+].code = #016
* group[=].element[=].target[=].display = "Chronic heart disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 016 - Chronic heart disease
* group[=].element[+].code = #53741008
* group[=].element[=].display = "Coronary arteriosclerosis [disorder]"
* group[=].element[=].target[+].code = #016
* group[=].element[=].target[=].display = "Chronic heart disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 016 - Chronic heart disease
* group[=].element[+].code = #79619009
* group[=].element[=].display = "Mitral valve stenosis [disorder]"
* group[=].element[=].target[+].code = #016
* group[=].element[=].target[=].display = "Chronic heart disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 016 - Chronic heart disease
* group[=].element[+].code = #698247007
* group[=].element[=].display = "Cardiac arrhythmia [disorder]"
* group[=].element[=].target[+].code = #016
* group[=].element[=].target[=].display = "Chronic heart disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 017 - Chronic lung disease
* group[=].element[+].code = #413839001
* group[=].element[=].display = "Chronic lung disease [disorder]"
* group[=].element[=].target[+].code = #017
* group[=].element[=].target[=].display = "Chronic lung disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 017 - Chronic lung disease
* group[=].element[+].code = #13645005
* group[=].element[=].display = "Chronic obstructive lung disease [disorder]"
* group[=].element[=].target[+].code = #017
* group[=].element[=].target[=].display = "Chronic lung disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 017 - Chronic lung disease
* group[=].element[+].code = #87433001
* group[=].element[=].display = "Pulmonary emphysema [disorder]"
* group[=].element[=].target[+].code = #017
* group[=].element[=].target[=].display = "Chronic lung disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 017 - Chronic lung disease
* group[=].element[+].code = #39871006
* group[=].element[=].display = "Chronic respiratory failure [disorder]"
* group[=].element[=].target[+].code = #017
* group[=].element[=].target[=].display = "Chronic lung disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 017 - Chronic lung disease
* group[=].element[+].code = #427896006
* group[=].element[=].display = "Chronic respiratory insufficiency [disorder]"
* group[=].element[=].target[+].code = #017
* group[=].element[=].target[=].display = "Chronic lung disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 017 - Chronic lung disease
* group[=].element[+].code = #17097001
* group[=].element[=].display = "Chronic disease of respiratory system [disorder]"
* group[=].element[=].target[+].code = #017
* group[=].element[=].target[=].display = "Chronic lung disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 018 - Laboratory Evidence of Immunity or confirmation of Hepatitis A disease
* group[=].element[+].code = #278971009
* group[=].element[=].display = "Hepatitis A Immune [Finding]"
* group[=].element[=].target[+].code = #018
* group[=].element[=].target[=].display = "Laboratory Evidence of Immunity or confirmation of Hepatitis A disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 019 - Laboratory Evidence of Immunity or confirmation of Hepatitis B disease
* group[=].element[+].code = #271511000
* group[=].element[=].display = "Hepatitis B Immune [Finding]"
* group[=].element[=].target[+].code = #019
* group[=].element[=].target[=].display = "Laboratory Evidence of Immunity or confirmation of Hepatitis B disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 020 - Laboratory Evidence of Immunity for Measles
* group[=].element[+].code = #371111005
* group[=].element[=].display = "Measles Immune [finding]"
* group[=].element[=].target[+].code = #020
* group[=].element[=].target[=].display = "Laboratory Evidence of Immunity for Measles"
* group[=].element[=].target[=].equivalence = #equivalent

// 021 - Laboratory Evidence of Immunity for Mumps
* group[=].element[+].code = #371112003
* group[=].element[=].display = "Mumps Immune [finding]"
* group[=].element[=].target[+].code = #021
* group[=].element[=].target[=].display = "Laboratory Evidence of Immunity for Mumps"
* group[=].element[=].target[=].equivalence = #equivalent

// 022 - Laboratory Evidence of Immunity for Rubella
* group[=].element[+].code = #278968001
* group[=].element[=].display = "Rubella Immune [finding]"
* group[=].element[=].target[+].code = #022
* group[=].element[=].target[=].display = "Laboratory Evidence of Immunity for Rubella"
* group[=].element[=].target[=].equivalence = #equivalent

// 023 - Laboratory Evidence of Immunity or confirmation of Varicella disease
* group[=].element[+].code = #371113008
* group[=].element[=].display = "Varicella Immune"
* group[=].element[=].target[+].code = #023
* group[=].element[=].target[=].display = "Laboratory Evidence of Immunity or confirmation of Varicella disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 024 - Healthcare provider verified history of or diagnosis of Varicella
* group[=].element[+].code = #38907003
* group[=].element[=].display = "Varicella [Disorder]"
* group[=].element[=].target[+].code = #024
* group[=].element[=].target[=].display = "Healthcare provider verified history of or diagnosis of Varicella"
* group[=].element[=].target[=].equivalence = #equivalent

// 025 - Healthcare provider verified history or diagnosis of Herpes Zoster
* group[=].element[+].code = #4740000
* group[=].element[=].display = "Herpes Zoster [Disorder]"
* group[=].element[=].target[+].code = #025
* group[=].element[=].target[=].display = "Healthcare provider verified history or diagnosis of Herpes Zoster"
* group[=].element[=].target[=].equivalence = #equivalent

// 026 - Persons with perinatal HIV infection who do not have evidence of severe immunosuppression and who were vaccinated with MMR before establishment of antiviral therapy [ART]
* group[=].element[+].code = #86406008
* group[=].element[=].display = "Human immunodeficiency virus infection [disorder]"
* group[=].element[=].target[+].code = #026
* group[=].element[=].target[=].display = "Persons with perinatal HIV infection who do not have evidence of severe immunosuppression and who were vaccinated with MMR before establishment of antiviral therapy [ART]"
* group[=].element[=].target[=].equivalence = #equivalent

// 026 - Persons with perinatal HIV infection who do not have evidence of severe immunosuppression and who were vaccinated with MMR before establishment of antiviral therapy [ART]
* group[=].element[+].code = #427314002
* group[=].element[=].display = "Antiviral therapy [procedure]"
* group[=].element[=].target[+].code = #026
* group[=].element[=].target[=].display = "Persons with perinatal HIV infection who do not have evidence of severe immunosuppression and who were vaccinated with MMR before establishment of antiviral therapy [ART]"
* group[=].element[=].target[=].equivalence = #equivalent

// 027 - Asthma
* group[=].element[+].code = #390798007
* group[=].element[=].display = "Asthma finding [finding]"
* group[=].element[=].target[+].code = #027
* group[=].element[=].target[=].display = "Asthma"
* group[=].element[=].target[=].equivalence = #equivalent

// 027 - Asthma
* group[=].element[+].code = #195967001
* group[=].element[=].display = "Asthma [disorder]"
* group[=].element[=].target[+].code = #027
* group[=].element[=].target[=].display = "Asthma"
* group[=].element[=].target[=].equivalence = #equivalent

// 028 - Intussusception
* group[=].element[+].code = #35327006
* group[=].element[=].display = "Intussusception [morphologic abnormality]"
* group[=].element[=].target[+].code = #028
* group[=].element[=].target[=].display = "Intussusception"
* group[=].element[=].target[=].equivalence = #equivalent

// 028 - Intussusception
* group[=].element[+].code = #49723003
* group[=].element[=].display = "Intussusception of intestine [disorder]"
* group[=].element[=].target[+].code = #028
* group[=].element[=].target[=].display = "Intussusception"
* group[=].element[=].target[=].equivalence = #equivalent

// 029 - Acute gastroenteritis
* group[=].element[+].code = #69776003
* group[=].element[=].display = "Acute gastroenteritis [disorder]"
* group[=].element[=].target[+].code = #029
* group[=].element[=].target[=].display = "Acute gastroenteritis"
* group[=].element[=].target[=].equivalence = #equivalent

// 031 - Tuberculosis
* group[=].element[+].code = #56717001
* group[=].element[=].display = "Tuberculosis [disorder]"
* group[=].element[=].target[+].code = #031
* group[=].element[=].target[=].display = "Tuberculosis"
* group[=].element[=].target[=].equivalence = #equivalent

// 033 - Taken influenza antiviral medications within the previous 48 hours
* group[=].element[+].code = #372763006
* group[=].element[=].display = "Amantadine [substance]"
* group[=].element[=].target[+].code = #033
* group[=].element[=].target[=].display = "Taken influenza antiviral medications within the previous 48 hours"
* group[=].element[=].target[=].equivalence = #equivalent

// 033 - Taken influenza antiviral medications within the previous 48 hours
* group[=].element[+].code = #51361008
* group[=].element[=].display = "Amantadine [product]"
* group[=].element[=].target[+].code = #033
* group[=].element[=].target[=].display = "Taken influenza antiviral medications within the previous 48 hours"
* group[=].element[=].target[=].equivalence = #equivalent

// 033 - Taken influenza antiviral medications within the previous 48 hours
* group[=].element[+].code = #372532009
* group[=].element[=].display = "Rimantadine [substance]"
* group[=].element[=].target[+].code = #033
* group[=].element[=].target[=].display = "Taken influenza antiviral medications within the previous 48 hours"
* group[=].element[=].target[=].equivalence = #equivalent

// 033 - Taken influenza antiviral medications within the previous 48 hours
* group[=].element[+].code = #108712009
* group[=].element[=].display = "Rimantadine [product]"
* group[=].element[=].target[+].code = #033
* group[=].element[=].target[=].display = "Taken influenza antiviral medications within the previous 48 hours"
* group[=].element[=].target[=].equivalence = #equivalent

// 033 - Taken influenza antiviral medications within the previous 48 hours
* group[=].element[+].code = #387010007
* group[=].element[=].display = "Zanamivir [substance]"
* group[=].element[=].target[+].code = #033
* group[=].element[=].target[=].display = "Taken influenza antiviral medications within the previous 48 hours"
* group[=].element[=].target[=].equivalence = #equivalent

// 033 - Taken influenza antiviral medications within the previous 48 hours
* group[=].element[+].code = #116100000
* group[=].element[=].display = "Zanamivir [product]"
* group[=].element[=].target[+].code = #033
* group[=].element[=].target[=].display = "Taken influenza antiviral medications within the previous 48 hours"
* group[=].element[=].target[=].equivalence = #equivalent

// 033 - Taken influenza antiviral medications within the previous 48 hours
* group[=].element[+].code = #412261005
* group[=].element[=].display = "Oseltamivir [substance]"
* group[=].element[=].target[+].code = #033
* group[=].element[=].target[=].display = "Taken influenza antiviral medications within the previous 48 hours"
* group[=].element[=].target[=].equivalence = #equivalent

// 033 - Taken influenza antiviral medications within the previous 48 hours
* group[=].element[+].code = #386142008
* group[=].element[=].display = "Oseltamivir [product]"
* group[=].element[=].target[+].code = #033
* group[=].element[=].target[=].display = "Taken influenza antiviral medications within the previous 48 hours"
* group[=].element[=].target[=].equivalence = #equivalent

// 034 - Receiving long-term aspirin therapy
* group[=].element[+].code = #405742008
* group[=].element[=].display = "Aspirin therapy finding [finding]"
* group[=].element[=].target[+].code = #034
* group[=].element[=].target[=].display = "Receiving long-term aspirin therapy"
* group[=].element[=].target[=].equivalence = #equivalent

// 036 - Men who have sex with men
* group[=].element[+].code = #76102007
* group[=].element[=].display = "Male homosexual [finding]"
* group[=].element[=].target[+].code = #036
* group[=].element[=].target[=].display = "Men who have sex with men"
* group[=].element[=].target[=].equivalence = #equivalent

// 036 - Men who have sex with men
* group[=].element[+].code = #225531006
* group[=].element[=].display = "Homosexual behavior [finding]"
* group[=].element[=].target[+].code = #036
* group[=].element[=].target[=].display = "Men who have sex with men"
* group[=].element[=].target[=].equivalence = #equivalent

// 037 - Not in a long-term, mutually monogamous relationship
* group[=].element[+].code = #225516002
* group[=].element[=].display = "Multiple sexual contacts [finding]"
* group[=].element[=].target[+].code = #037
* group[=].element[=].target[=].display = "Not in a long-term, mutually monogamous relationship"
* group[=].element[=].target[=].equivalence = #equivalent

// 037 - Not in a long-term, mutually monogamous relationship
* group[=].element[+].code = #228460004
* group[=].element[=].display = "Multiple current sexual partners [finding]"
* group[=].element[=].target[+].code = #037
* group[=].element[=].target[=].display = "Not in a long-term, mutually monogamous relationship"
* group[=].element[=].target[=].equivalence = #equivalent

// 037 - Not in a long-term, mutually monogamous relationship
* group[=].element[+].code = #228466005
* group[=].element[=].display = "Commitment to sexual relationship [observable entity]"
* group[=].element[=].target[+].code = #037
* group[=].element[=].target[=].display = "Not in a long-term, mutually monogamous relationship"
* group[=].element[=].target[=].equivalence = #equivalent

// 038 - Sex partner of Hepatitis B surface antigen-positive persons
* group[=].element[+].code = #225517006
* group[=].element[=].display = "Sexual partners [observable entity]"
* group[=].element[=].target[+].code = #038
* group[=].element[=].target[=].display = "Sex partner of Hepatitis B surface antigen-positive persons"
* group[=].element[=].target[=].equivalence = #equivalent

// 038 - Sex partner of Hepatitis B surface antigen-positive persons
* group[=].element[+].code = #11723008
* group[=].element[=].display = "Contact with [contextual qualifier] [qualifier value]"
* group[=].element[=].target[+].code = #038
* group[=].element[=].target[=].display = "Sex partner of Hepatitis B surface antigen-positive persons"
* group[=].element[=].target[=].equivalence = #equivalent

// 038 - Sex partner of Hepatitis B surface antigen-positive persons
* group[=].element[+].code = #165806002
* group[=].element[=].display = "Hepatitis B surface antigen positive [finding]"
* group[=].element[=].target[+].code = #038
* group[=].element[=].target[=].display = "Sex partner of Hepatitis B surface antigen-positive persons"
* group[=].element[=].target[=].equivalence = #equivalent

// 039 - Receives treatment for STD
* group[=].element[+].code = #305489005
* group[=].element[=].display = "Under care of genitourinary medicine physician [finding]"
* group[=].element[=].target[+].code = #039
* group[=].element[=].target[=].display = "Receives treatment for STD"
* group[=].element[=].target[=].equivalence = #equivalent

// 039 - Receives treatment for STD
* group[=].element[+].code = #305679000
* group[=].element[=].display = "Seen by genitourinary medicine physician [finding]"
* group[=].element[=].target[+].code = #039
* group[=].element[=].target[=].display = "Receives treatment for STD"
* group[=].element[=].target[=].equivalence = #equivalent

// 039 - Receives treatment for STD
* group[=].element[+].code = #8098009
* group[=].element[=].display = "Sexually transmitted infectious disease [disorder]"
* group[=].element[=].target[+].code = #039
* group[=].element[=].target[=].display = "Receives treatment for STD"
* group[=].element[=].target[=].equivalence = #equivalent

// 040 - Illicit drug use
* group[=].element[+].code = #307052004
* group[=].element[=].display = "Illicit drug use [finding]"
* group[=].element[=].target[+].code = #040
* group[=].element[=].target[=].display = "Illicit drug use"
* group[=].element[=].target[=].equivalence = #equivalent

// 040 - Illicit drug use
* group[=].element[+].code = #228366006
* group[=].element[=].display = "Finding relating to drug misuse behavior [finding]"
* group[=].element[=].target[+].code = #040
* group[=].element[=].target[=].display = "Illicit drug use"
* group[=].element[=].target[=].equivalence = #equivalent

// 041 - Illicit injection drug use
* group[=].element[+].code = #226034001
* group[=].element[=].display = "Injecting drug user [finding]"
* group[=].element[=].target[+].code = #041
* group[=].element[=].target[=].display = "Illicit injection drug use"
* group[=].element[=].target[=].equivalence = #equivalent

// 041 - Illicit injection drug use
* group[=].element[+].code = #228388006
* group[=].element[=].display = "Intravenous drug user [finding]"
* group[=].element[=].target[+].code = #041
* group[=].element[=].target[=].display = "Illicit injection drug use"
* group[=].element[=].target[=].equivalence = #equivalent

// 041 - Illicit injection drug use
* group[=].element[+].code = #145101000119102
* group[=].element[=].display = "Intravenous cocaine abuse [disorder]"
* group[=].element[=].target[+].code = #041
* group[=].element[=].target[=].display = "Illicit injection drug use"
* group[=].element[=].target[=].equivalence = #equivalent

// 041 - Illicit injection drug use
* group[=].element[+].code = #403746009
* group[=].element[=].display = "Skin lesion due to intravenous drug abuse [disorder]"
* group[=].element[=].target[+].code = #041
* group[=].element[=].target[=].display = "Illicit injection drug use"
* group[=].element[=].target[=].equivalence = #equivalent

// 041 - Illicit injection drug use
* group[=].element[+].code = #860699005
* group[=].element[=].display = "Deep vein thrombosis of lower extremity due to intravenous drug use [disorder]"
* group[=].element[=].target[+].code = #041
* group[=].element[=].target[=].display = "Illicit injection drug use"
* group[=].element[=].target[=].equivalence = #equivalent

// 042 - Smoke cigarettes
* group[=].element[+].code = #77176002
* group[=].element[=].display = "Smoker [finding]"
* group[=].element[=].target[+].code = #042
* group[=].element[=].target[=].display = "Smoke cigarettes"
* group[=].element[=].target[=].equivalence = #equivalent

// 043 - Alcoholism
* group[=].element[+].code = #228281002
* group[=].element[=].display = "Problem drinker [finding]"
* group[=].element[=].target[+].code = #043
* group[=].element[=].target[=].display = "Alcoholism"
* group[=].element[=].target[=].equivalence = #equivalent

// 043 - Alcoholism
* group[=].element[+].code = #7200002
* group[=].element[=].display = "Alcoholism [disorder]"
* group[=].element[=].target[+].code = #043
* group[=].element[=].target[=].display = "Alcoholism"
* group[=].element[=].target[=].equivalence = #equivalent

// 050 - Microbiologists routinely exposed to Neisseria meningitidis
* group[=].element[+].code = #159138004
* group[=].element[=].display = "Microbiologist [occupation]"
* group[=].element[=].target[+].code = #050
* group[=].element[=].target[=].display = "Microbiologists routinely exposed to Neisseria meningitidis"
* group[=].element[=].target[=].equivalence = #equivalent

// 050 - Microbiologists routinely exposed to Neisseria meningitidis
* group[=].element[+].code = #14698002
* group[=].element[=].display = "Medical microbiologist [occupation]"
* group[=].element[=].target[+].code = #050
* group[=].element[=].target[=].display = "Microbiologists routinely exposed to Neisseria meningitidis"
* group[=].element[=].target[=].equivalence = #equivalent

// 050 - Microbiologists routinely exposed to Neisseria meningitidis
* group[=].element[+].code = #24932003
* group[=].element[=].display = "Exposure to [contextual qualifier] [qualifier value]"
* group[=].element[=].target[+].code = #050
* group[=].element[=].target[=].display = "Microbiologists routinely exposed to Neisseria meningitidis"
* group[=].element[=].target[=].equivalence = #equivalent

// 050 - Microbiologists routinely exposed to Neisseria meningitidis
* group[=].element[+].code = #17872004
* group[=].element[=].display = "Neisseria meningitidis [organism]"
* group[=].element[=].target[+].code = #050
* group[=].element[=].target[=].display = "Microbiologists routinely exposed to Neisseria meningitidis"
* group[=].element[=].target[=].equivalence = #equivalent
// 159138004 also cited by observation 051
// 14698002 also cited by observation 051

// 051 - Microbiology laboratorians who work frequently with S. typhi
* group[=].element[+].code = #159282002
* group[=].element[=].display = "Laboratory technician [occupation]"
* group[=].element[=].target[+].code = #051
* group[=].element[=].target[=].display = "Microbiology laboratorians who work frequently with S. typhi"
* group[=].element[=].target[=].equivalence = #equivalent
// 24932003 also cited by observation 051

// 051 - Microbiology laboratorians who work frequently with S. typhi
* group[=].element[+].code = #5595000
* group[=].element[=].display = "Salmonella Typhi [organism]"
* group[=].element[=].target[+].code = #051
* group[=].element[=].target[=].display = "Microbiology laboratorians who work frequently with S. typhi"
* group[=].element[=].target[=].equivalence = #equivalent
// 159282002 also cited by observation 052
// 24932003 also cited by observation 052

// 052 - Laboratory personnel who might be exposed to YFV
* group[=].element[+].code = #26630006
* group[=].element[=].display = "Yellow fever virus [organism]"
* group[=].element[=].target[+].code = #052
* group[=].element[=].target[=].display = "Laboratory personnel who might be exposed to YFV"
* group[=].element[=].target[=].equivalence = #equivalent
// 159282002 also cited by observation 053
// 24932003 also cited by observation 053

// 053 - Rabies researchers
* group[=].element[+].code = #59881000
* group[=].element[=].display = "Rabies virus [organism]"
* group[=].element[=].target[+].code = #053
* group[=].element[=].target[=].display = "Rabies researchers"
* group[=].element[=].target[=].equivalence = #equivalent
// 159282002 also cited by observation 054
// 24932003 also cited by observation 054

// 054 - Laboratory workers who handle specimens that might contain polioviruses
* group[=].element[+].code = #44172002
* group[=].element[=].display = "Human poliovirus [organism]"
* group[=].element[=].target[+].code = #054
* group[=].element[=].target[=].display = "Laboratory workers who handle specimens that might contain polioviruses"
* group[=].element[=].target[=].equivalence = #equivalent

// 055 - Health care personnel
* group[=].element[+].code = #223366009
* group[=].element[=].display = "Healthcare professional [occupation]"
* group[=].element[=].target[+].code = #055
* group[=].element[=].target[=].display = "Health care personnel"
* group[=].element[=].target[=].equivalence = #equivalent
// 223366009 also cited by observation 056
// 24932003 also cited by observation 056
// 44172002 also cited by observation 056

// 057 - Public safety worker exposed to blood or infection body fluids
* group[=].element[+].code = #26369006
* group[=].element[=].display = "Public health nurse [occupation]"
* group[=].element[=].target[+].code = #057
* group[=].element[=].target[=].display = "Public safety worker exposed to blood or infection body fluids"
* group[=].element[=].target[=].equivalence = #equivalent

// 057 - Public safety worker exposed to blood or infection body fluids
* group[=].element[+].code = #68867008
* group[=].element[=].display = "Public health dentist [occupation]"
* group[=].element[=].target[+].code = #057
* group[=].element[=].target[=].display = "Public safety worker exposed to blood or infection body fluids"
* group[=].element[=].target[=].equivalence = #equivalent

// 057 - Public safety worker exposed to blood or infection body fluids
* group[=].element[+].code = #307969004
* group[=].element[=].display = "Public health officer [occupation]"
* group[=].element[=].target[+].code = #057
* group[=].element[=].target[=].display = "Public safety worker exposed to blood or infection body fluids"
* group[=].element[=].target[=].equivalence = #equivalent

// 057 - Public safety worker exposed to blood or infection body fluids
* group[=].element[+].code = #56466003
* group[=].element[=].display = "Public health physician [occupation]"
* group[=].element[=].target[+].code = #057
* group[=].element[=].target[=].display = "Public safety worker exposed to blood or infection body fluids"
* group[=].element[=].target[=].equivalence = #equivalent

// 057 - Public safety worker exposed to blood or infection body fluids
* group[=].element[+].code = #56079002
* group[=].element[=].display = "Public health veterinarian [occupation]"
* group[=].element[=].target[+].code = #057
* group[=].element[=].target[=].display = "Public safety worker exposed to blood or infection body fluids"
* group[=].element[=].target[=].equivalence = #equivalent

// 057 - Public safety worker exposed to blood or infection body fluids
* group[=].element[+].code = #60008001
* group[=].element[=].display = "Public health nutritionist [occupation]"
* group[=].element[=].target[+].code = #057
* group[=].element[=].target[=].display = "Public safety worker exposed to blood or infection body fluids"
* group[=].element[=].target[=].equivalence = #equivalent
// 24932003 also cited by observation 057

// 057 - Public safety worker exposed to blood or infection body fluids
* group[=].element[+].code = #87612001
* group[=].element[=].display = "Blood [substance]"
* group[=].element[=].target[+].code = #057
* group[=].element[=].target[=].display = "Public safety worker exposed to blood or infection body fluids"
* group[=].element[=].target[=].equivalence = #equivalent

// 057 - Public safety worker exposed to blood or infection body fluids
* group[=].element[+].code = #32457005
* group[=].element[=].display = "Body fluid [substance]"
* group[=].element[=].target[+].code = #057
* group[=].element[=].target[=].display = "Public safety worker exposed to blood or infection body fluids"
* group[=].element[=].target[=].equivalence = #equivalent
// 223366009 also cited by observation 059

// 059 - Occupational exposure for Hepatitis A
* group[=].element[+].code = #158942005
* group[=].element[=].display = "Residential child care worker [occupation]"
* group[=].element[=].target[+].code = #059
* group[=].element[=].target[=].display = "Occupational exposure for Hepatitis A"
* group[=].element[=].target[=].equivalence = #equivalent

// 059 - Occupational exposure for Hepatitis A
* group[=].element[+].code = #158939004
* group[=].element[=].display = "Child care officer [occupation]"
* group[=].element[=].target[+].code = #059
* group[=].element[=].target[=].display = "Occupational exposure for Hepatitis A"
* group[=].element[=].target[=].equivalence = #equivalent

// 059 - Occupational exposure for Hepatitis A
* group[=].element[+].code = #73851001
* group[=].element[=].display = "Plumber [general] [occupation]"
* group[=].element[=].target[+].code = #059
* group[=].element[=].target[=].display = "Occupational exposure for Hepatitis A"
* group[=].element[=].target[=].equivalence = #equivalent

// 059 - Occupational exposure for Hepatitis A
* group[=].element[+].code = #160157004
* group[=].element[=].display = "Sewerman [occupation]"
* group[=].element[=].target[+].code = #059
* group[=].element[=].target[=].display = "Occupational exposure for Hepatitis A"
* group[=].element[=].target[=].equivalence = #equivalent

// 059 - Occupational exposure for Hepatitis A
* group[=].element[+].code = #266006009
* group[=].element[=].display = "Food/drink processor [occupation]"
* group[=].element[=].target[+].code = #059
* group[=].element[=].target[=].display = "Occupational exposure for Hepatitis A"
* group[=].element[=].target[=].equivalence = #equivalent

// 059 - Occupational exposure for Hepatitis A
* group[=].element[+].code = #274272004
* group[=].element[=].display = "Catering services occupation [occupation]"
* group[=].element[=].target[+].code = #059
* group[=].element[=].target[=].display = "Occupational exposure for Hepatitis A"
* group[=].element[=].target[=].equivalence = #equivalent

// 059 - Occupational exposure for Hepatitis A
* group[=].element[+].code = #160133004
* group[=].element[=].display = "Packer - food/garden produce [occupation]"
* group[=].element[=].target[+].code = #059
* group[=].element[=].target[=].display = "Occupational exposure for Hepatitis A"
* group[=].element[=].target[=].equivalence = #equivalent

// 060 - Veterinarians and their staff
* group[=].element[+].code = #265940000
* group[=].element[=].display = "Animal health occupation [occupation]"
* group[=].element[=].target[+].code = #060
* group[=].element[=].target[=].display = "Veterinarians and their staff"
* group[=].element[=].target[=].equivalence = #equivalent

// 061 - Animal handlers
* group[=].element[+].code = #159091009
* group[=].element[=].display = "Trainer - performing animals [occupation]"
* group[=].element[=].target[+].code = #061
* group[=].element[=].target[=].display = "Animal handlers"
* group[=].element[=].target[=].equivalence = #equivalent
// 24932003 also cited by observation 062
// 59881000 also cited by observation 062

// 063 - Post secondary student
* group[=].element[+].code = #65853000
* group[=].element[=].display = "Student [occupation]"
* group[=].element[=].target[+].code = #063
* group[=].element[=].target[=].display = "Post secondary student"
* group[=].element[=].target[=].equivalence = #equivalent

// 063 - Post secondary student
* group[=].element[+].code = #257561002
* group[=].element[=].display = "Further education establishment [environment]"
* group[=].element[=].target[+].code = #063
* group[=].element[=].target[=].display = "Post secondary student"
* group[=].element[=].target[=].equivalence = #equivalent

// 066 - Chronic renal failure
* group[=].element[+].code = #90688005
* group[=].element[=].display = "Chronic renal failure syndrome [disorder]"
* group[=].element[=].target[+].code = #066
* group[=].element[=].target[=].display = "Chronic renal failure"
* group[=].element[=].target[=].equivalence = #equivalent

// 068 - In drug abuse treatment and prevention facility
* group[=].element[+].code = #20078004
* group[=].element[=].display = "Substance abuse treatment center [environment]"
* group[=].element[=].target[+].code = #068
* group[=].element[=].target[=].display = "In drug abuse treatment and prevention facility"
* group[=].element[=].target[=].equivalence = #equivalent

// 069 - In correctional facility
* group[=].element[+].code = #257656006
* group[=].element[=].display = "Penal institution [environment]"
* group[=].element[=].target[+].code = #069
* group[=].element[=].target[=].display = "In correctional facility"
* group[=].element[=].target[=].equivalence = #equivalent

// 070 - Persons at risk during an outbreak
* group[=].element[+].code = #410519009
* group[=].element[=].display = "At risk context [qualifier value]"
* group[=].element[=].target[+].code = #070
* group[=].element[=].target[=].display = "Persons at risk during an outbreak"
* group[=].element[=].target[=].equivalence = #equivalent

// 070 - Persons at risk during an outbreak
* group[=].element[+].code = #443684005
* group[=].element[=].display = "Disease outbreak [event]"
* group[=].element[=].target[+].code = #070
* group[=].element[=].target[=].display = "Persons at risk during an outbreak"
* group[=].element[=].target[=].equivalence = #equivalent
// 11723008 also cited by observation 071
// 165806002 also cited by observation 071

// 072 - Intimate exposure to a documented S. typhi carrier
* group[=].element[+].code = #170484009
* group[=].element[=].display = "Typhoid carrier [finding]"
* group[=].element[=].target[+].code = #072
* group[=].element[=].target[=].display = "Intimate exposure to a documented S. typhi carrier"
* group[=].element[=].target[=].equivalence = #equivalent

// 075 - Transgender person
* group[=].element[+].code = #12271241000119109
* group[=].element[=].display = "Transgender identify [finding]"
* group[=].element[=].target[+].code = #075
* group[=].element[=].target[=].display = "Transgender person"
* group[=].element[=].target[=].equivalence = #equivalent

// 076 - Progressive neurologic disorder
* group[=].element[+].code = #84757009
* group[=].element[=].display = "Epilepsy [disorder]"
* group[=].element[=].target[+].code = #076
* group[=].element[=].target[=].display = "Progressive neurologic disorder"
* group[=].element[=].target[=].equivalence = #equivalent

// 079 - Encephalopathy not attributable to another identifiable cause within 7 days of administration of a previous dose of Tdap, DTP, or DTaP vaccine
* group[=].element[+].code = #192711008
* group[=].element[=].display = "Post diphtheria vaccination encephalitis [disorder]"
* group[=].element[=].target[+].code = #079
* group[=].element[=].target[=].display = "Encephalopathy not attributable to another identifiable cause within 7 days of administration of a previous dose of Tdap, DTP, or DTaP vaccine"
* group[=].element[=].target[=].equivalence = #equivalent

// 079 - Encephalopathy not attributable to another identifiable cause within 7 days of administration of a previous dose of Tdap, DTP, or DTaP vaccine
* group[=].element[+].code = #192710009
* group[=].element[=].display = "Post tetanus vaccination encephalitis [disorder]"
* group[=].element[=].target[+].code = #079
* group[=].element[=].target[=].display = "Encephalopathy not attributable to another identifiable cause within 7 days of administration of a previous dose of Tdap, DTP, or DTaP vaccine"
* group[=].element[=].target[=].equivalence = #equivalent

// 079 - Encephalopathy not attributable to another identifiable cause within 7 days of administration of a previous dose of Tdap, DTP, or DTaP vaccine
* group[=].element[+].code = #192712001
* group[=].element[=].display = "Post pertussis vaccination encephalitis [disorder]"
* group[=].element[=].target[+].code = #079
* group[=].element[=].target[=].display = "Encephalopathy not attributable to another identifiable cause within 7 days of administration of a previous dose of Tdap, DTP, or DTaP vaccine"
* group[=].element[=].target[=].equivalence = #equivalent

// 080 - Adverse reaction to vaccine component
* group[=].element[+].code = #293104008
* group[=].element[=].display = "Vaccines adverse reaction [disorder]"
* group[=].element[=].target[+].code = #080
* group[=].element[=].target[=].display = "Adverse reaction to vaccine component"
* group[=].element[=].target[=].equivalence = #equivalent

// 081 - Severe allergic reaction after previous dose of Polio
* group[=].element[+].code = #293117006
* group[=].element[=].display = "Poliomyelitis vaccine adverse reaction [disorder]"
* group[=].element[=].target[+].code = #081
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Polio"
* group[=].element[=].target[=].equivalence = #equivalent

// 082 - Severe allergic reaction after previous dose of Japanese Encephalitis
* group[=].element[+].code = #451301000124103
* group[=].element[=].display = "Adverse reaction caused by Japanese encephalitis virus vaccine [disorder]"
* group[=].element[=].target[+].code = #082
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Japanese Encephalitis"
* group[=].element[=].target[=].equivalence = #equivalent

// 083 - Severe allergic reaction after previous dose of Rotavirus
* group[=].element[+].code = #429301000124101
* group[=].element[=].display = "Adverse reaction to rotavirus vaccine [disorder]"
* group[=].element[=].target[+].code = #083
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Rotavirus"
* group[=].element[=].target[=].equivalence = #equivalent

// 084 - Severe allergic reaction after previous dose of Typhoid
* group[=].element[+].code = #293122006
* group[=].element[=].display = "Typhoid vaccine adverse reaction [disorder]"
* group[=].element[=].target[+].code = #084
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Typhoid"
* group[=].element[=].target[=].equivalence = #equivalent

// 085 - Severe allergic reaction after previous dose of Influenza
* group[=].element[+].code = #420113004
* group[=].element[=].display = "Influenza virus vaccine adverse reaction [disorder]"
* group[=].element[=].target[+].code = #085
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Influenza"
* group[=].element[=].target[=].equivalence = #equivalent

// 086 - Severe allergic reaction after previous dose of Pertussis
* group[=].element[+].code = #293115003
* group[=].element[=].display = "Pertussis vaccine adverse reaction [disorder]"
* group[=].element[=].target[+].code = #086
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Pertussis"
* group[=].element[=].target[=].equivalence = #equivalent

// 087 - Severe allergic reaction after previous dose of Diphtheria
* group[=].element[+].code = #219085007
* group[=].element[=].display = "Adverse reaction to diphtheria vaccine [disorder]"
* group[=].element[=].target[+].code = #087
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Diphtheria"
* group[=].element[=].target[=].equivalence = #equivalent

// 088 - Severe allergic reaction after previous dose of Tetanus
* group[=].element[+].code = #219084006
* group[=].element[=].display = "Adverse reaction to tetanus vaccine [disorder]"
* group[=].element[=].target[+].code = #088
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Tetanus"
* group[=].element[=].target[=].equivalence = #equivalent

// 089 - Severe allergic reaction after previous dose of Varicella
* group[=].element[+].code = #451331000124106
* group[=].element[=].display = "Adverse reaction caused by varicella virus live vaccine [disorder]"
* group[=].element[=].target[+].code = #089
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Varicella"
* group[=].element[=].target[=].equivalence = #equivalent

// 090 - Severe allergic reaction after previous dose of HPV
* group[=].element[+].code = #429311000124103
* group[=].element[=].display = "Adverse reaction to human papillomavirus vaccine [disorder]"
* group[=].element[=].target[+].code = #090
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of HPV"
* group[=].element[=].target[=].equivalence = #equivalent

// 091 - Severe allergic reaction after previous dose of Measles
* group[=].element[+].code = #219096004
* group[=].element[=].display = "Adverse reaction to measles vaccine [disorder]"
* group[=].element[=].target[+].code = #091
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Measles"
* group[=].element[=].target[=].equivalence = #equivalent

// 092 - Severe allergic reaction after previous dose of Mumps
* group[=].element[+].code = #293114004
* group[=].element[=].display = "Mumps vaccine adverse reaction [disorder]"
* group[=].element[=].target[+].code = #092
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Mumps"
* group[=].element[=].target[=].equivalence = #equivalent

// 093 - Severe allergic reaction after previous dose of Rubella
* group[=].element[+].code = #293119009
* group[=].element[=].display = "Rubella vaccine adverse reaction [disorder]"
* group[=].element[=].target[+].code = #093
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Rubella"
* group[=].element[=].target[=].equivalence = #equivalent

// 094 - Severe allergic reaction after previous dose of Pneumococcal
* group[=].element[+].code = #293116002
* group[=].element[=].display = "Pneumococcal vaccine adverse reaction [disorder]"
* group[=].element[=].target[+].code = #094
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Pneumococcal"
* group[=].element[=].target[=].equivalence = #equivalent

// 095 - Severe allergic reaction after previous dose of Meningococcal
* group[=].element[+].code = #219088009
* group[=].element[=].display = "Adverse reaction to meningococcal vaccine [disorder]"
* group[=].element[=].target[+].code = #095
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Meningococcal"
* group[=].element[=].target[=].equivalence = #equivalent

// 095 - Severe allergic reaction after previous dose of Meningococcal
* group[=].element[+].code = #451111000124103
* group[=].element[=].display = "Adverse reaction caused by meningococcal conjugate vaccine [disorder]"
* group[=].element[=].target[+].code = #095
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Meningococcal"
* group[=].element[=].target[=].equivalence = #equivalent

// 096 - Severe allergic reaction after previous dose of Hepatitis A
* group[=].element[+].code = #293126009
* group[=].element[=].display = "Hepatitis A vaccine adverse reaction [disorder]"
* group[=].element[=].target[+].code = #096
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Hepatitis A"
* group[=].element[=].target[=].equivalence = #equivalent

// 097 - Severe allergic reaction after previous dose of Hepatitis B
* group[=].element[+].code = #293110008
* group[=].element[=].display = "Hepatitis B vaccine adverse reaction [disorder]"
* group[=].element[=].target[+].code = #097
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Hepatitis B"
* group[=].element[=].target[=].equivalence = #equivalent

// 098 - Severe allergic reaction after previous dose of Hib
* group[=].element[+].code = #293127000
* group[=].element[=].display = "Haemophilus influenzae Type B vaccine adverse reaction [disorder]"
* group[=].element[=].target[+].code = #098
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Hib"
* group[=].element[=].target[=].equivalence = #equivalent

// 099 - Severe allergic reaction after previous dose of Yellow Fever
* group[=].element[+].code = #219095000
* group[=].element[=].display = "Adverse reaction to yellow fever vaccine [disorder]"
* group[=].element[=].target[+].code = #099
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Yellow Fever"
* group[=].element[=].target[=].equivalence = #equivalent

// 100 - Severe allergic reaction after previous dose of live zoster
* group[=].element[+].code = #451291000124104
* group[=].element[=].display = "Adverse reaction caused by zoster vaccine [disorder]"
* group[=].element[=].target[+].code = #100
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of live zoster"
* group[=].element[=].target[=].equivalence = #equivalent

// 101 - Allergic reaction to egg protein
* group[=].element[+].code = #213020009
* group[=].element[=].display = "Egg protein allergy [disorder]"
* group[=].element[=].target[+].code = #101
* group[=].element[=].target[=].display = "Allergic reaction to egg protein"
* group[=].element[=].target[=].equivalence = #equivalent

// 101 - Allergic reaction to egg protein
* group[=].element[+].code = #91930004
* group[=].element[=].display = "Allergy to eggs [disorder]"
* group[=].element[=].target[+].code = #101
* group[=].element[=].target[=].display = "Allergic reaction to egg protein"
* group[=].element[=].target[=].equivalence = #equivalent

// 102 - Severe allergic reaction to gelatin
* group[=].element[+].code = #293309006
* group[=].element[=].display = "Gelatin adverse reaction [disorder]"
* group[=].element[=].target[+].code = #102
* group[=].element[=].target[=].display = "Severe allergic reaction to gelatin"
* group[=].element[=].target[=].equivalence = #equivalent

// 102 - Severe allergic reaction to gelatin
* group[=].element[+].code = #294847001
* group[=].element[=].display = "Gelatin allergy [disorder]"
* group[=].element[=].target[+].code = #102
* group[=].element[=].target[=].display = "Severe allergic reaction to gelatin"
* group[=].element[=].target[=].equivalence = #equivalent

// 104 - Allergic reaction to latex
* group[=].element[+].code = #300916003
* group[=].element[=].display = "Latex allergy [disorder]"
* group[=].element[=].target[+].code = #104
* group[=].element[=].target[=].display = "Allergic reaction to latex"
* group[=].element[=].target[=].equivalence = #equivalent

// 104 - Allergic reaction to latex
* group[=].element[+].code = #441593005
* group[=].element[=].display = "Anaphylaxis due to latex [disorder]"
* group[=].element[=].target[+].code = #104
* group[=].element[=].target[=].display = "Allergic reaction to latex"
* group[=].element[=].target[=].equivalence = #equivalent

// 106 - Severe allergic reaction to gentamicin
* group[=].element[+].code = #419522004
* group[=].element[=].display = "Gentamycin sensitivity [disorder]"
* group[=].element[=].target[+].code = #106
* group[=].element[=].target[=].display = "Severe allergic reaction to gentamicin"
* group[=].element[=].target[=].equivalence = #equivalent

// 106 - Severe allergic reaction to gentamicin
* group[=].element[+].code = #420094007
* group[=].element[=].display = "Gentamicin adverse reaction [disorder]"
* group[=].element[=].target[+].code = #106
* group[=].element[=].target[=].display = "Severe allergic reaction to gentamicin"
* group[=].element[=].target[=].equivalence = #equivalent

// 106 - Severe allergic reaction to gentamicin
* group[=].element[+].code = #294469003
* group[=].element[=].display = "Gentamicin allergy [disorder]"
* group[=].element[=].target[+].code = #106
* group[=].element[=].target[=].display = "Severe allergic reaction to gentamicin"
* group[=].element[=].target[=].equivalence = #equivalent

// 107 - Severe allergic reaction to neomycin
* group[=].element[+].code = #294468006
* group[=].element[=].display = "Neomycin allergy [disorder]"
* group[=].element[=].target[+].code = #107
* group[=].element[=].target[=].display = "Severe allergic reaction to neomycin"
* group[=].element[=].target[=].equivalence = #equivalent

// 107 - Severe allergic reaction to neomycin
* group[=].element[+].code = #292927007
* group[=].element[=].display = "Neomycin adverse reaction [disorder]"
* group[=].element[=].target[+].code = #107
* group[=].element[=].target[=].display = "Severe allergic reaction to neomycin"
* group[=].element[=].target[=].equivalence = #equivalent

// 108 - Severe allergic reaction to streptomycin
* group[=].element[+].code = #294466005
* group[=].element[=].display = "Streptomycin allergy [disorder]"
* group[=].element[=].target[+].code = #108
* group[=].element[=].target[=].display = "Severe allergic reaction to streptomycin"
* group[=].element[=].target[=].equivalence = #equivalent

// 108 - Severe allergic reaction to streptomycin
* group[=].element[+].code = #292925004
* group[=].element[=].display = "Streptomycin adverse reaction [disorder]"
* group[=].element[=].target[+].code = #108
* group[=].element[=].target[=].display = "Severe allergic reaction to streptomycin"
* group[=].element[=].target[=].equivalence = #equivalent

// 109 - Severe allergic reaction to polymyxin B
* group[=].element[+].code = #294530006
* group[=].element[=].display = "Polymyxin B allergy [disorder]"
* group[=].element[=].target[+].code = #109
* group[=].element[=].target[=].display = "Severe allergic reaction to polymyxin B"
* group[=].element[=].target[=].equivalence = #equivalent

// 109 - Severe allergic reaction to polymyxin B
* group[=].element[+].code = #292992006
* group[=].element[=].display = "Polymyxin B adverse reaction [disorder]"
* group[=].element[=].target[+].code = #109
* group[=].element[=].target[=].display = "Severe allergic reaction to polymyxin B"
* group[=].element[=].target[=].equivalence = #equivalent

// 110 - Hypersensitivity to yeast
* group[=].element[+].code = #703936006
* group[=].element[=].display = "Allergy to yeast [disorder]"
* group[=].element[=].target[+].code = #110
* group[=].element[=].target[=].display = "Hypersensitivity to yeast"
* group[=].element[=].target[=].equivalence = #equivalent

// 113 - Severe allergic reaction after previous dose of Rabies
* group[=].element[+].code = #293118001
* group[=].element[=].display = "Rabies vaccine adverse reaction [disorder]"
* group[=].element[=].target[+].code = #113
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Rabies"
* group[=].element[=].target[=].equivalence = #equivalent

// 114 - End stage renal disease
* group[=].element[+].code = #46177005
* group[=].element[=].display = "End stage renal disease [disorder]"
* group[=].element[=].target[+].code = #114
* group[=].element[=].target[=].display = "End stage renal disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 114 - End stage renal disease
* group[=].element[+].code = #443143006
* group[=].element[=].display = "Dependence on hemodialysis [finding]"
* group[=].element[=].target[+].code = #114
* group[=].element[=].target[=].display = "End stage renal disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 114 - End stage renal disease
* group[=].element[+].code = #714749008
* group[=].element[=].display = "Continuous renal replacement therapy [procedure]"
* group[=].element[=].target[+].code = #114
* group[=].element[=].target[=].display = "End stage renal disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 115 - Severe allergic reaction to protamine sulfate
* group[=].element[+].code = #64520006
* group[=].element[=].display = "Protamine sulfate [substance]"
* group[=].element[=].target[+].code = #115
* group[=].element[=].target[=].display = "Severe allergic reaction to protamine sulfate"
* group[=].element[=].target[=].equivalence = #equivalent

// 115 - Severe allergic reaction to protamine sulfate
* group[=].element[+].code = #294278007
* group[=].element[=].display = "Protamine allergy [disorder]"
* group[=].element[=].target[+].code = #115
* group[=].element[=].target[=].display = "Severe allergic reaction to protamine sulfate"
* group[=].element[=].target[=].equivalence = #equivalent

// 116 - Severe allergic reaction after previous dose of Meningococcal B
* group[=].element[+].code = #451281000124102
* group[=].element[=].display = "Adverse reaction caused by meningococcal group B vaccine [disorder]"
* group[=].element[=].target[+].code = #116
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of Meningococcal B"
* group[=].element[=].target[=].equivalence = #equivalent

// 119 - Severe allergic reaction after previous dose of cholera
* group[=].element[+].code = #219082005
* group[=].element[=].display = "Adverse reaction caused by cholera vaccine [disorder]"
* group[=].element[=].target[+].code = #119
* group[=].element[=].target[=].display = "Severe allergic reaction after previous dose of cholera"
* group[=].element[=].target[=].equivalence = #equivalent

// 121 - Homelessness
* group[=].element[+].code = #32911000
* group[=].element[=].display = "Homeless [finding]"
* group[=].element[=].target[+].code = #121
* group[=].element[=].target[=].display = "Homelessness"
* group[=].element[=].target[=].equivalence = #equivalent

// 132 - RBC [adenine-saline added] blood transfusion
* group[=].element[+].code = #116859006
* group[=].element[=].display = "Transfusion of blood product [procedure]"
* group[=].element[=].target[+].code = #132
* group[=].element[=].target[=].display = "RBC [adenine-saline added] blood transfusion"
* group[=].element[=].target[=].equivalence = #equivalent
// 116859006 also cited by observation 133
// 116859006 also cited by observation 134

// 135 - Plasma/platelet products blood transfusion
* group[=].element[+].code = #13569004
* group[=].element[=].display = "Transfusion of plasma [procedure]"
* group[=].element[=].target[+].code = #135
* group[=].element[=].target[=].display = "Plasma/platelet products blood transfusion"
* group[=].element[=].target[=].equivalence = #equivalent

// 135 - Plasma/platelet products blood transfusion
* group[=].element[+].code = #12719002
* group[=].element[=].display = "Platelet transfusion [procedure]"
* group[=].element[=].target[+].code = #135
* group[=].element[=].target[=].display = "Plasma/platelet products blood transfusion"
* group[=].element[=].target[=].equivalence = #equivalent

// 145 - B-lymphocyte [humoral] - Severe antibody deficiencies
* group[=].element[+].code = #65880007
* group[=].element[=].display = "X-linked agammaglobulinemia [disorder]"
* group[=].element[=].target[+].code = #145
* group[=].element[=].target[=].display = "B-lymphocyte [humoral] - Severe antibody deficiencies"
* group[=].element[=].target[=].equivalence = #equivalent

// 145 - B-lymphocyte [humoral] - Severe antibody deficiencies
* group[=].element[+].code = #23238000
* group[=].element[=].display = "Common variable agammaglobulinemia [disorder]"
* group[=].element[=].target[+].code = #145
* group[=].element[=].target[=].display = "B-lymphocyte [humoral] - Severe antibody deficiencies"
* group[=].element[=].target[=].equivalence = #equivalent

// 146 - B-lymphocyte [humoral] - Less severe antibody deficiencies
* group[=].element[+].code = #190979003
* group[=].element[=].display = "Selective immunoglobulin A deficiency [disorder]"
* group[=].element[=].target[+].code = #146
* group[=].element[=].target[=].display = "B-lymphocyte [humoral] - Less severe antibody deficiencies"
* group[=].element[=].target[=].equivalence = #equivalent

// 146 - B-lymphocyte [humoral] - Less severe antibody deficiencies
* group[=].element[+].code = #123785006
* group[=].element[=].display = "Immunoglobulin G subclass deficiency [finding]"
* group[=].element[=].target[+].code = #146
* group[=].element[=].target[=].display = "B-lymphocyte [humoral] - Less severe antibody deficiencies"
* group[=].element[=].target[=].equivalence = #equivalent
// 31323000 also cited by observation 147

// 147 - T-lymphocyte [cell-mediated and humoral] - Complete defects
* group[=].element[+].code = #77128003
* group[=].element[=].display = "DiGeorge sequence [disorder]"
* group[=].element[=].target[+].code = #147
* group[=].element[=].target[=].display = "T-lymphocyte [cell-mediated and humoral] - Complete defects"
* group[=].element[=].target[=].equivalence = #equivalent
// 77128003 also cited by observation 148

// 148 - T-lymphocyte [cell-mediated and humoral] - Partial defects
* group[=].element[+].code = #36070007
* group[=].element[=].display = "Wiskott-Aldrich syndrome [disorder]"
* group[=].element[=].target[+].code = #148
* group[=].element[=].target[=].display = "T-lymphocyte [cell-mediated and humoral] - Partial defects"
* group[=].element[=].target[=].equivalence = #equivalent

// 148 - T-lymphocyte [cell-mediated and humoral] - Partial defects
* group[=].element[+].code = #68504005
* group[=].element[=].display = "Ataxia-telangiectasia syndrome [disorder]"
* group[=].element[=].target[+].code = #148
* group[=].element[=].target[=].display = "T-lymphocyte [cell-mediated and humoral] - Partial defects"
* group[=].element[=].target[=].equivalence = #equivalent

// 151 - Persistent complement, properdin, or factor B deficiency
* group[=].element[+].code = #24743004
* group[=].element[=].display = "Complement deficiency disease [disorder]"
* group[=].element[=].target[+].code = #151
* group[=].element[=].target[=].display = "Persistent complement, properdin, or factor B deficiency"
* group[=].element[=].target[=].equivalence = #equivalent

// 151 - Persistent complement, properdin, or factor B deficiency
* group[=].element[+].code = #81166004
* group[=].element[=].display = "Properdin deficiency disease [disorder]"
* group[=].element[=].target[+].code = #151
* group[=].element[=].target[=].display = "Persistent complement, properdin, or factor B deficiency"
* group[=].element[=].target[=].equivalence = #equivalent

// 151 - Persistent complement, properdin, or factor B deficiency
* group[=].element[+].code = #234605000
* group[=].element[=].display = "Factor B deficiency [disorder]"
* group[=].element[=].target[+].code = #151
* group[=].element[=].target[=].display = "Persistent complement, properdin, or factor B deficiency"
* group[=].element[=].target[=].equivalence = #equivalent

// 152 - Phagocytic function - Chronic granulomatous disease
* group[=].element[+].code = #387759001
* group[=].element[=].display = "Chronic granulomatous disease [disorder]"
* group[=].element[=].target[+].code = #152
* group[=].element[=].target[=].display = "Phagocytic function - Chronic granulomatous disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 153 - Phagocytic function - Leukocyte adhesion defect, and myeloperoxidase deficiency
* group[=].element[+].code = #77358003
* group[=].element[=].display = "Congenital leukocyte adherence deficiency [disorder]"
* group[=].element[=].target[+].code = #153
* group[=].element[=].target[=].display = "Phagocytic function - Leukocyte adhesion defect, and myeloperoxidase deficiency"
* group[=].element[=].target[=].equivalence = #equivalent

// 153 - Phagocytic function - Leukocyte adhesion defect, and myeloperoxidase deficiency
* group[=].element[+].code = #234433009
* group[=].element[=].display = "Myeloperoxidase deficiency [disorder]"
* group[=].element[=].target[+].code = #153
* group[=].element[=].target[=].display = "Phagocytic function - Leukocyte adhesion defect, and myeloperoxidase deficiency"
* group[=].element[=].target[=].equivalence = #equivalent

// 154 - HIV/AIDS - severely immunocompromised
* group[=].element[+].code = #62479008
* group[=].element[=].display = "Acquired immune deficiency syndrome [disorder]"
* group[=].element[=].target[+].code = #154
* group[=].element[=].target[=].display = "HIV/AIDS - severely immunocompromised"
* group[=].element[=].target[=].equivalence = #equivalent
// 62479008 also cited by observation 155

// 157 - Solid organ transplantation
* group[=].element[+].code = #313039003
* group[=].element[=].display = "Solid organ transplant [procedure]"
* group[=].element[=].target[+].code = #157
* group[=].element[=].target[=].display = "Solid organ transplantation"
* group[=].element[=].target[=].equivalence = #equivalent

// 158 - Immunosuppressive therapy
* group[=].element[+].code = #86553008
* group[=].element[=].display = "Immunosuppressive therapy [procedure]"
* group[=].element[=].target[+].code = #158
* group[=].element[=].target[=].display = "Immunosuppressive therapy"
* group[=].element[=].target[=].equivalence = #equivalent

// 159 - Radiation therapy
* group[=].element[+].code = #53438000
* group[=].element[=].display = "Radiation therapy procedure or service [procedure]"
* group[=].element[=].target[+].code = #159
* group[=].element[=].target[=].display = "Radiation therapy"
* group[=].element[=].target[=].equivalence = #equivalent

// 160 - Anatomical or functional asplenia
* group[=].element[+].code = #707147002
* group[=].element[=].display = "Asplenia [disorder]"
* group[=].element[=].target[+].code = #160
* group[=].element[=].target[=].display = "Anatomical or functional asplenia"
* group[=].element[=].target[=].equivalence = #equivalent

// 161 - Chronic kidney disease
* group[=].element[+].code = #709044004
* group[=].element[=].display = "Chronic kidney disease [disorder]"
* group[=].element[=].target[+].code = #161
* group[=].element[=].target[=].display = "Chronic kidney disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 167 - Nephrotic Syndrome
* group[=].element[+].code = #52254009
* group[=].element[=].display = "Nephrotic syndrome [disorder]"
* group[=].element[=].target[+].code = #167
* group[=].element[=].target[=].display = "Nephrotic Syndrome"
* group[=].element[=].target[=].equivalence = #equivalent

// 168 - Chemotherapy
* group[=].element[+].code = #367336001
* group[=].element[=].display = "Chemotherapy [procedure]"
* group[=].element[=].target[+].code = #168
* group[=].element[=].target[=].display = "Chemotherapy"
* group[=].element[=].target[=].equivalence = #equivalent

// 169 - History of sexual abuse or assault
* group[=].element[+].code = #213017001
* group[=].element[=].display = "Sexual abuse [event]"
* group[=].element[=].target[+].code = #169
* group[=].element[=].target[=].display = "History of sexual abuse or assault"
* group[=].element[=].target[=].equivalence = #equivalent

// 169 - History of sexual abuse or assault
* group[=].element[+].code = #422608009
* group[=].element[=].display = "Sexual assault [finding]"
* group[=].element[=].target[+].code = #169
* group[=].element[=].target[=].display = "History of sexual abuse or assault"
* group[=].element[=].target[=].equivalence = #equivalent

// 169 - History of sexual abuse or assault
* group[=].element[+].code = #248110007
* group[=].element[=].display = "Sexual assault [event]"
* group[=].element[=].target[+].code = #169
* group[=].element[=].target[=].display = "History of sexual abuse or assault"
* group[=].element[=].target[=].equivalence = #equivalent

// 170 - Onset of pregnancy
* group[=].element[+].code = #248986005
* group[=].element[=].display = "Estimated date of conception [observable entity]"
* group[=].element[=].target[+].code = #170
* group[=].element[=].target[=].display = "Onset of pregnancy"
* group[=].element[=].target[=].equivalence = #equivalent
// 451291000124104 also cited by observation 172

// 178 - Leukemia
* group[=].element[+].code = #93143009
* group[=].element[=].display = "Leukemia, disease [disorder]"
* group[=].element[=].target[+].code = #178
* group[=].element[=].target[=].display = "Leukemia"
* group[=].element[=].target[=].equivalence = #equivalent

// 179 - Lymphoma
* group[=].element[+].code = #399600009
* group[=].element[=].display = "Lymphoma [finding]"
* group[=].element[=].target[+].code = #179
* group[=].element[=].target[=].display = "Lymphoma"
* group[=].element[=].target[=].equivalence = #equivalent

// 180 - Hodgkin's disease
* group[=].element[+].code = #118599009
* group[=].element[=].display = "Hodgkin's disease [disorder]"
* group[=].element[=].target[+].code = #180
* group[=].element[=].target[=].display = "Hodgkin's disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 181 - Multiple myeloma
* group[=].element[+].code = #109989006
* group[=].element[=].display = "Multiple myeloma [disorder]"
* group[=].element[=].target[+].code = #181
* group[=].element[=].target[=].display = "Multiple myeloma"
* group[=].element[=].target[=].equivalence = #equivalent
// 86406008 also cited by observation 186

// 191 - Receipt of CAR-T-cell therapy
* group[=].element[+].code = #1156961008
* group[=].element[=].display = "Chimeric antigen receptor T-cell immunotherapy [procedure]"
* group[=].element[=].target[+].code = #191
* group[=].element[=].target[=].display = "Receipt of CAR-T-cell therapy"
* group[=].element[=].target[=].equivalence = #equivalent

// 198 - Cancer
* group[=].element[+].code = #363346000
* group[=].element[=].display = "Malignant neoplastic disease [disorder]"
* group[=].element[=].target[+].code = #198
* group[=].element[=].target[=].display = "Cancer"
* group[=].element[=].target[=].equivalence = #equivalent

// 199 - Interstitial lung disease
* group[=].element[+].code = #233703007
* group[=].element[=].display = "Interstitial lung disease [disorder]"
* group[=].element[=].target[+].code = #199
* group[=].element[=].target[=].display = "Interstitial lung disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 200 - Cystic fibrosis
* group[=].element[+].code = #190905008
* group[=].element[=].display = "cystic fibrosis [disorder]"
* group[=].element[=].target[+].code = #200
* group[=].element[=].target[=].display = "Cystic fibrosis"
* group[=].element[=].target[=].equivalence = #equivalent

// 201 - Pulmonary hypertension
* group[=].element[+].code = #70995007
* group[=].element[=].display = "Pulmonary hypertension [disorder]"
* group[=].element[=].target[+].code = #201
* group[=].element[=].target[=].display = "Pulmonary hypertension"
* group[=].element[=].target[=].equivalence = #equivalent

// 202 - Dementia
* group[=].element[+].code = #52448006
* group[=].element[=].display = "Dimensia [disorder]"
* group[=].element[=].target[+].code = #202
* group[=].element[=].target[=].display = "Dementia"
* group[=].element[=].target[=].equivalence = #equivalent

// 203 - Down syndrome
* group[=].element[+].code = #41040004
* group[=].element[=].display = "Complete trisomy 21 syndrome [disorder]"
* group[=].element[=].target[+].code = #203
* group[=].element[=].target[=].display = "Down syndrome"
* group[=].element[=].target[=].equivalence = #equivalent

// 204 - Obesity
* group[=].element[+].code = #238131007
* group[=].element[=].display = "Overweight [finding]"
* group[=].element[=].target[+].code = #204
* group[=].element[=].target[=].display = "Obesity"
* group[=].element[=].target[=].equivalence = #equivalent

// 204 - Obesity
* group[=].element[+].code = #414915002
* group[=].element[=].display = "Obese [finding]"
* group[=].element[=].target[+].code = #204
* group[=].element[=].target[=].display = "Obesity"
* group[=].element[=].target[=].equivalence = #equivalent

// 204 - Obesity
* group[=].element[+].code = #83911000119104
* group[=].element[=].display = "Severe obesity [disorder]"
* group[=].element[=].target[+].code = #204
* group[=].element[=].target[=].display = "Obesity"
* group[=].element[=].target[=].equivalence = #equivalent

// 205 - Thalassemia
* group[=].element[+].code = #40108008
* group[=].element[=].display = "Thalassemia [disorder]"
* group[=].element[=].target[+].code = #205
* group[=].element[=].target[=].display = "Thalassemia"
* group[=].element[=].target[=].equivalence = #equivalent

// 206 - Cerebrovascular disease
* group[=].element[+].code = #62914000
* group[=].element[=].display = "Cerebrovascular disease [disorder]"
* group[=].element[=].target[+].code = #206
* group[=].element[=].target[=].display = "Cerebrovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent
// 13645005 also cited by observation 214
// 87433001 also cited by observation 215

// 245 - American Indian or Alaskan Native
* group[=].element[+].code = #413490006
* group[=].element[=].display = "American Indian or Alaska Native [racial group]"
* group[=].element[=].target[+].code = #245
* group[=].element[=].target[=].display = "American Indian or Alaskan Native"
* group[=].element[=].target[=].equivalence = #equivalent

// 253 - Moderate persistent or severe persistent asthma
* group[=].element[+].code = #370219009
* group[=].element[=].display = "Moderate Asthma [disorder]"
* group[=].element[=].target[+].code = #253
* group[=].element[=].target[=].display = "Moderate persistent or severe persistent asthma"
* group[=].element[=].target[=].equivalence = #equivalent

// 253 - Moderate persistent or severe persistent asthma
* group[=].element[+].code = #427295004
* group[=].element[=].display = "Moderate Persistent Asthma [disorder]"
* group[=].element[=].target[+].code = #253
* group[=].element[=].target[=].display = "Moderate persistent or severe persistent asthma"
* group[=].element[=].target[=].equivalence = #equivalent

// 253 - Moderate persistent or severe persistent asthma
* group[=].element[+].code = #370221004
* group[=].element[=].display = "Severe Asthma [disorder]"
* group[=].element[=].target[+].code = #253
* group[=].element[=].target[=].display = "Moderate persistent or severe persistent asthma"
* group[=].element[=].target[=].equivalence = #equivalent

// 253 - Moderate persistent or severe persistent asthma
* group[=].element[+].code = #426656000
* group[=].element[=].display = "Severe Persistent Asthma [disorder]"
* group[=].element[=].target[+].code = #253
* group[=].element[=].target[=].display = "Moderate persistent or severe persistent asthma"
* group[=].element[=].target[=].equivalence = #equivalent

// 253 - Moderate persistent or severe persistent asthma
* group[=].element[+].code = #5281000124103
* group[=].element[=].display = "Persistent Asthma [disorder]"
* group[=].element[=].target[+].code = #253
* group[=].element[=].target[=].display = "Moderate persistent or severe persistent asthma"
* group[=].element[=].target[=].equivalence = #equivalent

// 253 - Moderate persistent or severe persistent asthma
* group[=].element[+].code = #2360001000004109
* group[=].element[=].display = "Steroid dependent asthma [disorder]"
* group[=].element[=].target[+].code = #253
* group[=].element[=].target[=].display = "Moderate persistent or severe persistent asthma"
* group[=].element[=].target[=].equivalence = #equivalent

// 254 - Chronic cardiovascular disease
* group[=].element[+].code = #128292002
* group[=].element[=].display = "Chronic disease of cardiovascular system [disorder]"
* group[=].element[=].target[+].code = #254
* group[=].element[=].target[=].display = "Chronic cardiovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 254 - Chronic cardiovascular disease
* group[=].element[+].code = #400047006
* group[=].element[=].display = "Peripheral vascular disease [disorder]"
* group[=].element[=].target[+].code = #254
* group[=].element[=].target[=].display = "Chronic cardiovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 254 - Chronic cardiovascular disease
* group[=].element[+].code = #21631000119105
* group[=].element[=].display = "Limb ischemia [disorder]"
* group[=].element[=].target[+].code = #254
* group[=].element[=].target[=].display = "Chronic cardiovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 254 - Chronic cardiovascular disease
* group[=].element[+].code = #63491006
* group[=].element[=].display = "Intermittent claudication [finding]"
* group[=].element[=].target[+].code = #254
* group[=].element[=].target[=].display = "Chronic cardiovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 254 - Chronic cardiovascular disease
* group[=].element[+].code = #65198009
* group[=].element[=].display = "Arterial thrombosis [disorder]"
* group[=].element[=].target[+].code = #254
* group[=].element[=].target[=].display = "Chronic cardiovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 254 - Chronic cardiovascular disease
* group[=].element[+].code = #111354009
* group[=].element[=].display = "Chronic vascular insufficiency of intestine [disorder]"
* group[=].element[=].target[+].code = #254
* group[=].element[=].target[=].display = "Chronic cardiovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent
// 70995007 also cited by observation 254

// 254 - Chronic cardiovascular disease
* group[=].element[+].code = #59282003
* group[=].element[=].display = "Pulmonary embolism [disorder]"
* group[=].element[=].target[+].code = #254
* group[=].element[=].target[=].display = "Chronic cardiovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 254 - Chronic cardiovascular disease
* group[=].element[+].code = #17920008
* group[=].element[=].display = "Portal vein thrombosis [disorder]"
* group[=].element[=].target[+].code = #254
* group[=].element[=].target[=].display = "Chronic cardiovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 254 - Chronic cardiovascular disease
* group[=].element[+].code = #67362008
* group[=].element[=].display = "Aortic aneurysm [disorder]"
* group[=].element[=].target[+].code = #254
* group[=].element[=].target[=].display = "Chronic cardiovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 254 - Chronic cardiovascular disease
* group[=].element[+].code = #233996000
* group[=].element[=].display = "Type II dissection of thoracic aorta [disorder]"
* group[=].element[=].target[+].code = #254
* group[=].element[=].target[=].display = "Chronic cardiovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 254 - Chronic cardiovascular disease
* group[=].element[+].code = #301899003
* group[=].element[=].display = "Dissection of proximal aorta [disorder]"
* group[=].element[=].target[+].code = #254
* group[=].element[=].target[=].display = "Chronic cardiovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 254 - Chronic cardiovascular disease
* group[=].element[+].code = #233997009
* group[=].element[=].display = "Dissection of distal aorta [disorder]"
* group[=].element[=].target[+].code = #254
* group[=].element[=].target[=].display = "Chronic cardiovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 254 - Chronic cardiovascular disease
* group[=].element[+].code = #27631000146108
* group[=].element[=].display = "Dissection of aortic arch [disorder]"
* group[=].element[=].target[+].code = #254
* group[=].element[=].target[=].display = "Chronic cardiovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 254 - Chronic cardiovascular disease
* group[=].element[+].code = #45894003
* group[=].element[=].display = "Medionecrosis of aorta [disorder]"
* group[=].element[=].target[+].code = #254
* group[=].element[=].target[=].display = "Chronic cardiovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 254 - Chronic cardiovascular disease
* group[=].element[+].code = #1303726005
* group[=].element[=].display = "Dissection of infrarenal aorta [disorder]"
* group[=].element[=].target[+].code = #254
* group[=].element[=].target[=].display = "Chronic cardiovascular disease"
* group[=].element[=].target[=].equivalence = #equivalent

// 256 - Diabetes mellitus complicated by chronic kidney disease
* group[=].element[+].code = #127013003
* group[=].element[=].display = "Disorder of kidney due to diabetes mellitus [disorder]"
* group[=].element[=].target[+].code = #256
* group[=].element[=].target[=].display = "Diabetes mellitus complicated by chronic kidney disease"
* group[=].element[=].target[=].equivalence = #equivalent
// 83911000119104 also cited by observation 257

// 257 - Severe obesity
* group[=].element[+].code = #408512008
* group[=].element[=].display = "Body mass index 40+ - severely obese [finding]"
* group[=].element[=].target[+].code = #257
* group[=].element[=].target[=].display = "Severe obesity"
* group[=].element[=].target[=].equivalence = #equivalent

// 258 - Chronic hematologic disorders
* group[=].element[+].code = #414027002
* group[=].element[=].display = "Disorder of hematopoietic structure [disorder]"
* group[=].element[=].target[+].code = #258
* group[=].element[=].target[=].display = "Chronic hematologic disorders"
* group[=].element[=].target[=].equivalence = #equivalent

// 258 - Chronic hematologic disorders
* group[=].element[+].code = #417357006
* group[=].element[=].display = "Sickling disorder due to hemoglobin S [disorder]"
* group[=].element[=].target[+].code = #258
* group[=].element[=].target[=].display = "Chronic hematologic disorders"
* group[=].element[=].target[=].equivalence = #equivalent
// 40108008 also cited by observation 258
// 417357006 also cited by observation 259

// 260 - Neurologic or neuromuscular conditions causing impaired airway clearance or respiratory muscle weakness
* group[=].element[+].code = #350586651000119105
* group[=].element[=].display = "Chronic respiratory failure due to neuromuscular disease [disorder]"
* group[=].element[=].target[+].code = #260
* group[=].element[=].target[=].display = "Neurologic or neuromuscular conditions causing impaired airway clearance or respiratory muscle weakness"
* group[=].element[=].target[=].equivalence = #equivalent

// 260 - Neurologic or neuromuscular conditions causing impaired airway clearance or respiratory muscle weakness
* group[=].element[+].code = #67750007
* group[=].element[=].display = "Ineffective airway clearance [finding]"
* group[=].element[=].target[+].code = #260
* group[=].element[=].target[=].display = "Neurologic or neuromuscular conditions causing impaired airway clearance or respiratory muscle weakness"
* group[=].element[=].target[=].equivalence = #equivalent

// 261 - Resident of a nursing home
* group[=].element[+].code = #160734000
* group[=].element[=].display = "Lives in nursing home [finding]"
* group[=].element[=].target[+].code = #261
* group[=].element[=].target[=].display = "Resident of a nursing home"
* group[=].element[=].target[=].equivalence = #equivalent

// 262 - Frailty
* group[=].element[+].code = #248279007
* group[=].element[=].display = "Frailty [finding]"
* group[=].element[=].target[+].code = #262
* group[=].element[=].target[=].display = "Frailty"
* group[=].element[=].target[=].equivalence = #equivalent

// 263 - Diabetes mellitus complicated by neuropathy
* group[=].element[+].code = #230572002
* group[=].element[=].display = "Neuropathy due to diabetes mellitus [disorder]"
* group[=].element[=].target[+].code = #263
* group[=].element[=].target[=].display = "Diabetes mellitus complicated by neuropathy"
* group[=].element[=].target[=].equivalence = #equivalent

// 264 - Diabetes mellitus complicated by retinopathy
* group[=].element[+].code = #4855003
* group[=].element[=].display = "Retinopathy due to diabetes mellitus [disorder]"
* group[=].element[=].target[+].code = #264
* group[=].element[=].target[=].display = "Diabetes mellitus complicated by retinopathy"
* group[=].element[=].target[=].equivalence = #equivalent

// 266 - Diabetes requiring treatment with insulin
* group[=].element[+].code = #170747006
* group[=].element[=].display = "Diabetic on insulin [finding]"
* group[=].element[=].target[+].code = #266
* group[=].element[=].target[=].display = "Diabetes requiring treatment with insulin"
* group[=].element[=].target[=].equivalence = #equivalent

// 268 - Islet Transplantation
* group[=].element[+].code = #128531006
* group[=].element[=].display = "Islet cell transplant [procedure]"
* group[=].element[=].target[+].code = #268
* group[=].element[=].target[=].display = "Islet Transplantation"
* group[=].element[=].target[=].equivalence = #equivalent

// 269 - Transplantation
* group[=].element[+].code = #77465005
* group[=].element[=].display = "Transplantation [procedure]"
* group[=].element[=].target[+].code = #269
* group[=].element[=].target[=].display = "Transplantation"
* group[=].element[=].target[=].equivalence = #equivalent

// 273 - Immunoglobulin deficiency
* group[=].element[+].code = #124950009
* group[=].element[=].display = "Deficiency of immunoglobulin [disorder]"
* group[=].element[=].target[+].code = #273
* group[=].element[=].target[=].display = "Immunoglobulin deficiency"
* group[=].element[=].target[=].equivalence = #equivalent

// 279 - Hemoglobinopathy disorder
* group[=].element[+].code = #80141007
* group[=].element[=].display = "hemoglobinopathy [disorder]"
* group[=].element[=].target[+].code = #279
* group[=].element[=].target[=].display = "Hemoglobinopathy disorder"
* group[=].element[=].target[=].equivalence = #equivalent

// 280 - Chronic lung disease of prematurity
* group[=].element[+].code = #67569000
* group[=].element[=].display = "Bronchopulmonary dysplasia of newborn [disorder]"
* group[=].element[=].target[+].code = #280
* group[=].element[=].target[=].display = "Chronic lung disease of prematurity"
* group[=].element[=].target[=].equivalence = #equivalent
