CodeSystem:  CdsiObservationCodes
Id: cdsi-observation-codes
Title: "CDSI Observation Codes"
Description:  "Observations and Conditions that are important to indications or contraindications in vaccine forecasting"
* #001 "001"
  "Patient seeks protection"
* #002 "002"
  "Undergoing elective splenectomy"
* #003 "003"
  "Immunocompromised"
* #004 "004"
  "Recipient of a hematopoietic stem cell transplant"
* #005 "005"
  "Hepatitis C virus infection"
* #006 "006"
  "Receives clotting factor concentrates"
* #007 "007"
  "Pregnant"
* #008 "008"
  "Travel to an area of active cholera transmission"
* #009 "009"
  "Breastfeeding"
* #010 "010"
  "Cerebrospinal fluid leaks"
* #011 "011"
  "Cochlear implants"
* #012 "012"
  "Family history of altered immunocompetence"
* #013 "013"
  "Severe Combined Immunodeficiency [SCID]"
* #014 "014"
  "Diabetes"
* #015 "015"
  "Chronic liver disease"
* #016 "016"
  "Chronic heart disease"
* #017 "017"
  "Chronic lung disease"
* #018 "018"
  "Laboratory Evidence of Immunity or confirmation of Hepatitis A disease"
* #019 "019"
  "Laboratory Evidence of Immunity or confirmation of Hepatitis B disease"
* #020 "020"
  "Laboratory Evidence of Immunity for Measles"
* #021 "021"
  "Laboratory Evidence of Immunity for Mumps"
* #022 "022"
  "Laboratory Evidence of Immunity for Rubella"
* #023 "023"
  "Laboratory Evidence of Immunity or confirmation of Varicella disease"
* #024 "024"
  "Healthcare provider verified history of or diagnosis of Varicella"
* #025 "025"
  "Healthcare provider verified history or diagnosis of Herpes Zoster"
* #026 "026"
  "Persons with perinatal HIV infection who do not have evidence of severe immunosuppression and who were vaccinated with MMR before establishment of antiviral therapy [ART]"
* #027 "027"
  "Asthma"
* #028 "028"
  "Intussusception"
* #029 "029"
  "Acute gastroenteritis"
* #030 "030"
  "Acute febrile illness"
* #031 "031"
  "Tuberculosis"
* #032 "032"
  "Dialysis patient"
* #033 "033"
  "Taken influenza antiviral medications within the previous 48 hours"
* #034 "034"
  "Receiving long-term aspirin therapy"
* #035 "035"
  "Antimicrobial or antimalarial taken within 72 hours"
* #036 "036"
  "Men who have sex with men"
* #037 "037"
  "Not in a long-term, mutually monogamous relationship"
* #038 "038"
  "Sex partner of Hepatitis B surface antigen-positive persons"
* #039 "039"
  "Receives treatment for STD"
* #040 "040"
  "Illicit drug use"
* #041 "041"
  "Illicit injection drug use"
* #042 "042"
  "Smoke cigarettes"
* #043 "043"
  "Alcoholism"
* #044 "044"
  "Anticipate close personal contact with international adoptee"
* #045 "045"
  "Travel to country with a Yellow Fever vaccination entry requirement"
* #046 "046"
  "College students living in residence halls"
* #047 "047"
  "Resident of area at risk for exposure to the disease"
* #048 "048"
  "Travelling Internationally"
* #049 "049"
  "Working with Hepatitis A virus in research setting"
* #050 "050"
  "Microbiologists routinely exposed to Neisseria meningitidis"
* #051 "051"
  "Microbiology laboratorians who work frequently with S. typhi"
* #052 "052"
  "Laboratory personnel who might be exposed to YFV"
* #053 "053"
  "Rabies researchers"
* #054 "054"
  "Laboratory workers who handle specimens that might contain polioviruses"
* #055 "055"
  "Health care personnel"
* #056 "056"
  "Health-care workers who have close contact with patients who might be excreting wild polioviruses"
* #057 "057"
  "Public safety worker exposed to blood or infection body fluids"
* #058 "058"
  "Staff of institution for persons with developmental disabilities"
* #059 "059"
  "Occupational exposure for Hepatitis A"
* #060 "060"
  "Veterinarians and their staff"
* #061 "061"
  "Animal handlers"
* #062 "062"
  "Persons whose activities bring them into frequent contact with rabies virus or potentially rabid animals"
* #063 "063"
  "Post secondary student"
* #064 "064"
  "Military recruits"
* #065 "065"
  "Client of institution for persons with developmental disabilities"
* #066 "066"
  "Chronic renal failure"
* #068 "068"
  "In drug abuse treatment and prevention facility"
* #069 "069"
  "In correctional facility"
* #070 "070"
  "Persons at risk during an outbreak"
* #071 "071"
  "Household contact with hepatitis B surface antigen-positive persons"
* #072 "072"
  "Intimate exposure to a documented S. typhi carrier"
* #073 "073"
  "Household and close contacts of immunocompromised persons"
* #074 "074"
  "Negative serological screening for varicella"
* #075 "075"
  "Transgender person"
* #076 "076"
  "Progressive neurologic disorder"
* #077 "077"
  "Received inactivated or unknown measles vaccine between 1963-1967"
* #078 "078"
  "Received killed or unknown Mumps vaccine before 1979"
* #079 "079"
  "Encephalopathy not attributable to another identifiable cause within 7 days of administration of a previous dose of Tdap, DTP, or DTaP vaccine"
* #080 "080"
  "Adverse reaction to vaccine component"
* #081 "081"
  "Severe allergic reaction after previous dose of Polio"
* #082 "082"
  "Severe allergic reaction after previous dose of Japanese Encephalitis"
* #083 "083"
  "Severe allergic reaction after previous dose of Rotavirus"
* #084 "084"
  "Severe allergic reaction after previous dose of Typhoid"
* #085 "085"
  "Severe allergic reaction after previous dose of Influenza"
* #086 "086"
  "Severe allergic reaction after previous dose of Pertussis"
* #087 "087"
  "Severe allergic reaction after previous dose of Diphtheria"
* #088 "088"
  "Severe allergic reaction after previous dose of Tetanus"
* #089 "089"
  "Severe allergic reaction after previous dose of Varicella"
* #090 "090"
  "Severe allergic reaction after previous dose of HPV"
* #091 "091"
  "Severe allergic reaction after previous dose of Measles"
* #092 "092"
  "Severe allergic reaction after previous dose of Mumps"
* #093 "093"
  "Severe allergic reaction after previous dose of Rubella"
* #094 "094"
  "Severe allergic reaction after previous dose of Pneumococcal"
* #095 "095"
  "Severe allergic reaction after previous dose of Meningococcal"
* #096 "096"
  "Severe allergic reaction after previous dose of Hepatitis A"
* #097 "097"
  "Severe allergic reaction after previous dose of Hepatitis B"
* #098 "098"
  "Severe allergic reaction after previous dose of Hib"
* #099 "099"
  "Severe allergic reaction after previous dose of Yellow Fever"
* #100 "100"
  "Severe allergic reaction after previous dose of live zoster"
* #101 "101"
  "Allergic reaction to egg protein"
* #102 "102"
  "Severe allergic reaction to gelatin"
* #103 "103"
  "Severe allergic reaction to arginine"
* #104 "104"
  "Allergic reaction to latex"
* #105 "105"
  "Severe allergic reaction to chicken protein"
* #106 "106"
  "Severe allergic reaction to gentamicin"
* #107 "107"
  "Severe allergic reaction to neomycin"
* #108 "108"
  "Severe allergic reaction to streptomycin"
* #109 "109"
  "Severe allergic reaction to polymyxin B"
* #110 "110"
  "Hypersensitivity to yeast"
* #111 "111"
  "Hypersensitivity to the preservative 2-phenoxyethanol"
* #112 "112"
  "Hypersensitivity to alum"
* #113 "113"
  "Severe allergic reaction after previous dose of Rabies"
* #114 "114"
  "End stage renal disease"
* #115 "115"
  "Severe allergic reaction to protamine sulfate"
* #116 "116"
  "Severe allergic reaction after previous dose of Meningococcal B"
* #117 "117"
  "Severe allergic reaction to diphtheria toxoid"
* #118 "118"
  "Severe allergic reaction to tetanus toxoid"
* #119 "119"
  "Severe allergic reaction after previous dose of cholera"
* #120 "120"
  "Begin Date of antiviral therapy [ART]"
* #121 "121"
  "Homelessness"
* #122 "122"
  "Severe allergic reaction after previous dose of COVID-19"
* #123 "123"
  "Severe allergic reaction after previous dose of Ebola"
* #124 "124"
  "Severe allergic reaction to rice protein "
* #125 "125"
  "Tetanus IG administration"
* #126 "126"
  "Hep A IG administration"
* #127 "127"
  "Hep B IG administration"
* #128 "128"
  "Rabies IG administration"
* #129 "129"
  "Varicella IG administration"
* #130 "130"
  "Measles prophylaxis IG administration - Standard"
* #131 "131"
  "Measles prophylaxis IG administration - Immunocompromised Contact"
* #132 "132"
  "RBC [adenine-saline added] blood transfusion"
* #133 "133"
  "Packed RBC blood transfusion"
* #134 "134"
  "Whole blood transfusion"
* #135 "135"
  "Plasma/platelet products blood transfusion"
* #136 "136"
  "Cytomegalovirus IGIV"
* #137 "137"
  "IGIV - Replacement therapy for immune deficiencies"
* #138 "138"
  "IGIV - Immune thrombocytopenic purpura treatment"
* #139 "139"
  "IGIV - Postexposure varicella prophylaxis"
* #140 "140"
  "IGIV - Immune thrombocytopenic purpura treatment"
* #141 "141"
  "IGIV - Kawasaki disease"
* #142 "142"
  "Travel to or working in countries that have high or intermediate endemicity of Hepatitis A"
* #143 "143"
  "Travel to areas or countries where polio is epidemic or endemic"
* #144 "144"
  "International travel with possible contact with animals in areas where rabies is enzootic and immediate access to appropriate medical care might be limited"
* #145 "145"
  "B-lymphocyte [humoral] - Severe antibody deficiencies"
* #146 "146"
  "B-lymphocyte [humoral] - Less severe antibody deficiencies"
* #147 "147"
  "T-lymphocyte [cell-mediated and humoral] - Complete defects"
* #148 "148"
  "T-lymphocyte [cell-mediated and humoral] - Partial defects"
* #149 "149"
  "T-lymphocyte [cell-mediated and humoral] - interferon-gamma/Interleukin 12 axis deficiencies"
* #150 "150"
  "T-lymphocyte [cell-mediated and humoral] - interferon-gamma or interferon-alpha"
* #151 "151"
  "Persistent complement, properdin, or factor B deficiency"
* #152 "152"
  "Phagocytic function - Chronic granulomatous disease"
* #153 "153"
  "Phagocytic function - Leukocyte adhesion defect, and myeloperoxidase deficiency"
* #154 "154"
  "HIV/AIDS - severely immunocompromised"
* #155 "155"
  "HIV/AIDS - not severely immunocompromised"
* #156 "156"
  "Generalized malignant neoplasm"
* #157 "157"
  "Transplantation"
* #158 "158"
  "Immunosuppressive therapy"
* #159 "159"
  "Radiation therapy"
* #160 "160"
  "Anatomical or functional asplenia"
* #161 "161"
  "Chronic kidney disease"
* #162 "162"
  "Travel to areas at risk for Yellow Fever transmission"
* #163 "163"
  "Travel to areas in which there is a recognized risk of exposure to S. typhi"
* #164 "164"
  "Travel to or are residents of countries in which meningococcal disease is hyperendemic or epidemic"
* #165 "165"
  "Longer-term (e.g., 1 month or more) travel to a JE-endemic area"
* #166 "166"
  "Travel to countries with high or intermediate prevalence of chronic HBV infection"
* #167 "167"
  "Nephrotic Syndrome"
* #168 "168"
  "Chemotherapy"
* #169 "169"
  "History of sexual abuse or assault"
* #170 "170"
  "Onset of pregnancy"
* #171 "171"
  "Date of hematopoietic stem cell transplant"
* #172 "172"
  "Severe allergic reaction after previous dose of recombinant zoster"
* #173 "173"
  "Moving to JE-endemic country to take up residence"
* #174 "174"
  "Frequent travel to JE-endemic areas"
* #175 "175"
  "Patient seeks Hepatitis A protection"
* #176 "176"
  "Patient seeks Hepatitis B protection"
* #177 "177"
  "Patient seeks Meningococcal B protection"
* #178 "178"
  "Leukemia"
* #179 "179"
  "Lymphoma"
* #180 "180"
  "Hodgkin's disease"
* #181 "181"
  "Multiple myeloma"
* #182 "182"
  "Ebola virus outbreak response"
* #183 "183"
  "Health care personnel at federally designated Ebola treatment center in U.S."
* #184 "184"
  "Laboratorians or other staff at biosafety level 4 facilities in U.S."
* #185 "185"
  "Persons in settings that provide services to adults with high proportion of those persons have risk factors for HAV infection"
* #186 "186"
  "HIV Infection"
* #187 "187"
  "Allergic reaction to polysorbate 80"
* #188 "188"
  "Known allergy to Polyethylene glycol [PEG]"
* #189 "189"
  "Active treatment for solid tumors"
* #190 "190"
  "Active treatment for hematologic malignancies"
* #191 "191"
  "Receipt of CAR-T-cell therapy"
* #192 "192"
  "Severe allergic reaction after previous dose of any egg-based IIV or LAIV influenza vaccine"
* #193 "193"
  "Severe allergic reaction after previous dose of any ccIIV influenza vaccine"
* #194 "194"
  "Severe allergic reaction after previous dose of any RIV influenza vaccine"
* #195 "195"
  "Occupations at increased risk for COVID-19 exposure and transmission"
* #196 "196"
  "Residing in an institutional setting at increased risk for COVID-19 exposure and transmission"
* #197 "197"
  "Resident of a long term care facility"
* #198 "198"
  "Cancer"
* #199 "199"
  "Interstitial lung disease"
* #200 "200"
  "Cystic fibrosis"
* #201 "201"
  "Pulmonary hypertension"
* #202 "202"
  "Dementia"
* #203 "203"
  "Down syndrome"
* #204 "204"
  "Obesity"
* #205 "205"
  "Thalassemia"
* #206 "206"
  "Cerebrovascular disease"
* #207 "207"
  "Substance use disorder"
* #208 "208"
  "Mental Health conditions"
* #209 "209"
  "History of thrombosis with thrombocytopenia following the Janssen COVID-19 Vaccine or any other adenovirus-vectored COVID-19 vaccines"
* #210 "210"
  "Severe allergic reaction after previous dose of Dengue vaccine"
* #211 "211"
  "Evidence of previous dengue infection and living in areas where dengue is endemic"
* #212 "212"
  "Health care personnel involved in the care and transport of patients with suspected or confirmed Ebola virus disease at Special Pathogen Treatment Centers"
* #213 "213"
  "Laboratorians and support staff members at Laboratory Response Network (LRN) facilities that handle specimens that might contain replication-competent Ebola virus in the United States"
* #214 "214"
  "Chronic obstructive pulmonary disease"
* #215 "215"
  "Emphysema"
* #216 "216"
  "Iatrogenic Immunosuppression"
* #217 "217"
  "Persons working in rabies vaccine production facilities"
* #218 "218"
  "Persons performing testing for rabies in diagnostic laboratories"
* #219 "219"
  "Persons who frequently handle bats"
* #220 "220"
  "Persons who frequently have contact with bats"
* #221 "221"
  "Persons who frequently enter high-density bat environments"
* #222 "222"
  "Persons who frequently perform animal necropsies"
* #223 "223"
  "Severe allergic reaction after previous dose of orthopoxvirus vaccine"
* #224 "224"
  "History or presence of atopic dermatitis"
* #225 "225"
  "Household contact with history or presence of atopic dermatitis"
* #226 "226"
  "Active exfoliative skin conditions"
* #227 "227"
  "Household contact with active exfoliative skin conditions"
* #228 "228"
  "Household contact is pregnant"
* #229 "229"
  "Age is less than 1 year"
* #230 "230"
  "Household contact who is less than 1 year of age"
* #231 "231"
  "3 or more known major cardiac risk factors"
* #232 "232"
  "Research laboratory personnel working with more virulent orthopoxviruses (e.g., Variola virus or mpox virus)"
* #233 "233"
  "Clinical laboratory personnel performing diagnostic testing for more virulent orthopoxviruses (e.g., Variola virus or mpox virus)"
* #234 "234"
  "Designated response team members working with more virulent orthopoxviruses (e.g., Variola virus or mpox virus)"
* #235 "235"
  "Healthcare personnel who care for patients infected with more virulent orthopoxviruses (e.g., Variola virus or mpox virus)"
* #236 "236"
  "Research laboratory personnel working with less virulent orthopoxviruses (e.g., Vaccinia virus or Cowpox virus)"
* #237 "237"
  "Clinical laboratory personnel performing diagnostic testing for less virulent orthopoxviruses (e.g., Vaccinia virus or Cowpox virus)"
* #238 "238"
  "Designated response team members working with less virulent orthopoxviruses (e.g., Vaccinia virus or Cowpox virus)"
* #239 "239"
  "Healthcare personnel who administer ACAM2000"
* #240 "240"
  "Healthcare personnel who care for patients infected with less virulent orthopoxviruses (e.g., Vaccinia virus or Cowpox virus)"
* #241 "241"
  "Known exposure to mpox"
* #242 "242"
  "Presumed exposure to mpox"
* #243 "243"
  "Lack of laboratory confirmation of a previous Dengue infection"
* #244 "244"
  "Severe allergic reaction after previous dose of RSV vaccine"
* #245 "245"
  "American Indian or Alaskan Native"
* #246 "246"
  "Severe immunocompromise"
* #247 "247"
  "Gay, bisexual, and other men who have sex with men, transgender or nonbinary peope who in the past 6 months have had one of the following:  1) A new diagnosis of ≥ 1 sexually transmitted disease 2)  More than one sex partner 3)  Sex at a commercial sex venue 4)   Sex in association with a large public event in a geographic area where mpox transmission is occurring"
* #248 "248"
  "Sexual partners of gay, bisexual, and other men who have sex with men, transgender or nonbinary peope who in the past 6 months have had one of the following:  1) A new diagnosis of ≥ 1 sexually transmitted disease 2)  More than one sex partner 3)  Sex at a commercial sex venue 4)   Sex in association with a large public event in a geographic area where mpox transmission is occurring"
* #249 "249"
  "Moving or traveling to an area where TBE is endemic and will have extensive exposure to ticks because of their planned outdoor activities and itinerary"
* #250 "250"
  "Moving or traveling to an area where TBE is endemic who might engage in outdoor activities in areas where ticks are likely to be found"
* #251 "251"
  "Laboratory workers with a potential for exposure to TBE virus"
* #252 "252"
  "Severe allergic reaction after previous dose of Tick-borne Encephalitis vaccine"