ValueSet: VaccineConditionCodesSnomed
Id: vaccine-condition-codes-snomed
Title: "Vaccine Condition Codes"
Description: "Value set for conditions based on SNOMED CT, that may impact immunization."
* include codes from system http://snomed.info/sct where concept is-a #370388006 //Patient Immunocompromised 
* include codes from system http://snomed.info/sct where concept is-a #50711007 //Viral hepatitis type C [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #77386006 //Patient currently pregnant [finding] 
* include codes from system http://snomed.info/sct where concept is-a #102874004 //Possible pregnancy [finding] 
* include codes from system http://snomed.info/sct where concept is-a #255409004 //Pregnant woman [person] 
* include codes from system http://snomed.info/sct where concept is-a #413712001 //Breastfeeding [mother] [observable entity] 
* include codes from system http://snomed.info/sct where concept is-a #230744007 //Cerebrospinal fluid leak [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #449840001 //Cochlear prosthesis in situ [finding] 
* include codes from system http://snomed.info/sct where concept is-a #43252007 //Cochlear prosthesis, device [physical object] 
* include codes from system http://snomed.info/sct where concept is-a #31323000 //Severe combined immunodeficiency disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #73211009 //Diabetes mellitus [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #328383001 //Chronic liver disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #19943007 //Cirrhosis of liver [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #128238001 //Chronic heart disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #42343007 //Congestive heart failure [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #57809008 //Myocardial disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #12770006 //Cyanotic congenital heart disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #413839001 //Chronic lung disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #13645005 //Chronic obstructive lung disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #87433001 //Pulmonary emphysema [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #278971009 //Hepatitis A Immune [Finding] 
* include codes from system http://snomed.info/sct where concept is-a #271511000 //Hepatitis B Immune [Finding] 
* include codes from system http://snomed.info/sct where concept is-a #371111005 //Measles Immune [finding] 
* include codes from system http://snomed.info/sct where concept is-a #371112003 //Mumps Immune [finding] 
* include codes from system http://snomed.info/sct where concept is-a #278968001 //Rubella Immune [finding] 
* include codes from system http://snomed.info/sct where concept is-a #371113008 //Varicella Immune 
* include codes from system http://snomed.info/sct where concept is-a #38907003 //Varicella [Disorder] 
* include codes from system http://snomed.info/sct where concept is-a #4740000 //Herpes Zoster [Disorder] 
* include codes from system http://snomed.info/sct where concept is-a #86406008 //Human immunodeficiency virus infection [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #390798007 //Asthma finding [finding] 
* include codes from system http://snomed.info/sct where concept is-a #195967001 //Asthma [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #35327006 //Intussusception [morphologic abnormality] 
* include codes from system http://snomed.info/sct where concept is-a #49723003 //Intussusception of intestine [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #69776003 //Acute gastroenteritis [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #56717001 //Tuberculosis [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #405742008 //Aspirin therapy finding [finding] 
* include codes from system http://snomed.info/sct where concept is-a #76102007 //Male homosexual [finding] 
* include codes from system http://snomed.info/sct where concept is-a #225531006 //Homosexual behavior [finding] 
* include codes from system http://snomed.info/sct where concept is-a #225516002 //Multiple sexual contacts [finding] 
* include codes from system http://snomed.info/sct where concept is-a #228460004 //Multiple current sexual partners [finding] 
* include codes from system http://snomed.info/sct where concept is-a #228466005 //Commitment to sexual relationship [observable entity] 
* include codes from system http://snomed.info/sct where concept is-a #225517006 //Sexual partners [observable entity] 
* include codes from system http://snomed.info/sct where concept is-a #11723008 //Contact with [contextual qualifier] [qualifier value] 
* include codes from system http://snomed.info/sct where concept is-a #165806002 //Hepatitis B surface antigen positive [finding] 
* include codes from system http://snomed.info/sct where concept is-a #305489005 //Under care of genitourinary medicine physician [finding] 
* include codes from system http://snomed.info/sct where concept is-a #305679000 //Seen by genitourinary medicine physician [finding] 
* include codes from system http://snomed.info/sct where concept is-a #8098009 //Sexually transmitted infectious disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #307052004 //Illicit drug use [finding] 
* include codes from system http://snomed.info/sct where concept is-a #228366006 //Finding relating to drug misuse behavior [finding] 
* include codes from system http://snomed.info/sct where concept is-a #226034001 //Injecting drug user [finding] 
* include codes from system http://snomed.info/sct where concept is-a #228388006 //Intravenous drug user  [finding] 
* include codes from system http://snomed.info/sct where concept is-a #145101000119102 //Intravenous cocaine abuse [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #403746009 //Skin lesion due to intravenous drug abuse [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #860699005 //Deep vein thrombosis of lower extremity due to intravenous drug use [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #77176002 //Smoker [finding] 
* include codes from system http://snomed.info/sct where concept is-a #228281002 //Problem drinker [finding] 
* include codes from system http://snomed.info/sct where concept is-a #7200002 //Alcoholism [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #159138004 //Microbiologist [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #14698002 //Medical microbiologist [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #24932003 //Exposure to [contextual qualifier] [qualifier value] 
* include codes from system http://snomed.info/sct where concept is-a #17872004 //Neisseria meningitidis [organism] 
* include codes from system http://snomed.info/sct where concept is-a #159138004 //Microbiologist [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #14698002 //Medical microbiologist [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #159282002 //Laboratory technician [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #24932003 //Exposure to [contextual qualifier] [qualifier value] 
* include codes from system http://snomed.info/sct where concept is-a #5595000 //Salmonella Typhi [organism] 
* include codes from system http://snomed.info/sct where concept is-a #159282002 //Laboratory technician [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #24932003 //Exposure to [contextual qualifier] [qualifier value] 
* include codes from system http://snomed.info/sct where concept is-a #26630006 //Yellow fever virus [organism] 
* include codes from system http://snomed.info/sct where concept is-a #159282002 //Laboratory technician [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #24932003 //Exposure to [contextual qualifier] [qualifier value] 
* include codes from system http://snomed.info/sct where concept is-a #59881000 //Rabies virus [organism] 
* include codes from system http://snomed.info/sct where concept is-a #159282002 //Laboratory technician [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #24932003 //Exposure to [contextual qualifier] [qualifier value] 
* include codes from system http://snomed.info/sct where concept is-a #44172002 //Human poliovirus [organism] 
* include codes from system http://snomed.info/sct where concept is-a #223366009 //Healthcare professional [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #223366009 //Healthcare professional [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #24932003 //Exposure to [contextual qualifier] [qualifier value] 
* include codes from system http://snomed.info/sct where concept is-a #44172002 //Human poliovirus [organism] 
* include codes from system http://snomed.info/sct where concept is-a #26369006 //Public health nurse [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #68867008 //Public health dentist [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #307969004 //Public health officer [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #56466003 //Public health physician [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #56079002 //Public health veterinarian [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #60008001 //Public health nutritionist [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #24932003 //Exposure to [contextual qualifier] [qualifier value] 
* include codes from system http://snomed.info/sct where concept is-a #87612001 //Blood [substance] 
* include codes from system http://snomed.info/sct where concept is-a #32457005 //Body fluid [substance] 
* include codes from system http://snomed.info/sct where concept is-a #223366009 //Healthcare professional [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #158942005 //Residential child care worker [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #158939004 //Child care officer [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #73851001 //Plumber [general] [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #160157004 //Sewerman [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #266006009 //Food/drink processor [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #274272004 //Catering services occupation [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #160133004 //Packer - food/garden produce [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #265940000 //Animal health occupation [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #159091009 //Trainer - performing animals [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #24932003 //Exposure to [contextual qualifier] [qualifier value] 
* include codes from system http://snomed.info/sct where concept is-a #59881000 //Rabies virus [organism] 
* include codes from system http://snomed.info/sct where concept is-a #65853000 //Student [occupation] 
* include codes from system http://snomed.info/sct where concept is-a #257561002 //Further education establishment [environment] 
* include codes from system http://snomed.info/sct where concept is-a #90688005 //Chronic renal failure syndrome [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #20078004 //Substance abuse treatment center [environment] 
* include codes from system http://snomed.info/sct where concept is-a #257656006 //Penal institution [environment] 
* include codes from system http://snomed.info/sct where concept is-a #410519009 //At risk context [qualifier value] 
* include codes from system http://snomed.info/sct where concept is-a #443684005 //Disease outbreak [event] 
* include codes from system http://snomed.info/sct where concept is-a #11723008 //Contact with [contextual qualifier] [qualifier value] 
* include codes from system http://snomed.info/sct where concept is-a #165806002 //Hepatitis B surface antigen positive [finding] 
* include codes from system http://snomed.info/sct where concept is-a #170484009 //Typhoid carrier [finding] 
* include codes from system http://snomed.info/sct where concept is-a #12271241000119109 //Transgender identify [finding] 
* include codes from system http://snomed.info/sct where concept is-a #84757009 //Epilepsy [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #192711008 //Post diphtheria vaccination encephalitis [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #192710009 //Post tetanus vaccination encephalitis [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #192712001 //Post pertussis vaccination encephalitis [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #293104008 //Vaccines adverse reaction [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #293117006 //Poliomyelitis vaccine adverse reaction [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #451301000124103 //Adverse reaction caused by Japanese encephalitis virus vaccine [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #429301000124101 //Adverse reaction to rotavirus vaccine [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #293122006 //Typhoid vaccine adverse reaction [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #420113004 //Influenza virus vaccine adverse reaction [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #293115003 //Pertussis vaccine adverse reaction [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #219085007 //Adverse reaction to diphtheria vaccine [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #219084006 //Adverse reaction to tetanus vaccine [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #451331000124106 //Adverse reaction caused by varicella virus live vaccine [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #429311000124103 //Adverse reaction to human papillomavirus vaccine [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #219096004 //Adverse reaction to measles vaccine [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #293114004 //Mumps vaccine adverse reaction [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #293119009 //Rubella vaccine adverse reaction [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #293116002 //Pneumococcal vaccine adverse reaction [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #2219088009 //Adverse reaction to meningococcal vaccine [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #451111000124103 //Adverse reaction caused by meningococcal conjugate vaccine [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #293126009 //Hepatitis A vaccine adverse reaction [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #293110008 //Hepatitis B vaccine adverse reaction [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #293127000 //Haemophilus influenzae Type B vaccine adverse reaction [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #219095000 //Adverse reaction to yellow fever vaccine [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #451291000124104 //Adverse reaction caused by zoster vaccine [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #213020009 //Egg protein allergy [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #91930004 //Allergy to eggs [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #293309006 //Gelatin adverse reaction [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #294847001 //Gelatin allergy [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #300916003 //Latex allergy [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #441593005 //Anaphylaxis due to latex [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #419522004 //Gentamycin sensitivity [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #420094007 //Gentamicin adverse reaction [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #294469003 //Gentamicin allergy [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #294468006 //Neomycin allergy [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #292927007 //Neomycin adverse reaction [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #294466005 //Streptomycin allergy [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #292925004 //Streptomycin adverse reaction [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #294530006 //Polymyxin B allergy [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #292992006 //Polymyxin B adverse reaction [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #703936006 //Allergy to yeast [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #293118001 //Rabies vaccine adverse reaction [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #46177005 //End stage renal disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #294278007 //Protamine allergy [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #451281000124102 //Adverse reaction caused by meningococcal group B vaccine [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #219082005 //Adverse reaction caused by cholera vaccine [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #32911000 //Homeless [finding] 
* include codes from system http://snomed.info/sct where concept is-a #65880007 //X-linked agammaglobulinemia [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #23238000 //Common variable agammaglobulinemia [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #190979003 //Selective immunoglobulin A deficiency [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #123785006 //Immunoglobulin G subclass deficiency [finding] 
* include codes from system http://snomed.info/sct where concept is-a #31323000 //Severe combined immunodeficiency disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #77128003 //DiGeorge sequence [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #77128003 //DiGeorge sequence [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #36070007 //Wiskott-Aldrich syndrome [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #68504005 //Ataxia-telangiectasia syndrome [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #24743004 //Complement deficiency disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #24743004 //Complement deficiency disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #81166004 //Properdin deficiency disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #234605000 //Factor B deficiency [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #387759001 //Chronic granulomatous disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #77358003 //Congenital leukocyte adherence deficiency [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #234433009 //Myeloperoxidase deficiency [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #62479008 //Acquired immune deficiency syndrome [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #62479008 //Acquired immune deficiency syndrome [disorder]
* include codes from system http://snomed.info/sct where concept is-a #707147002 //Asplenia [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #709044004 //Chronic kidney disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #52254009 //Nephrotic syndrome [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #213017001 //Sexual abuse [event] 
* include codes from system http://snomed.info/sct where concept is-a #422608009 //Sexual assault [finding 
* include codes from system http://snomed.info/sct where concept is-a #248110007 //Sexual assault [event] 
* include codes from system http://snomed.info/sct where concept is-a #248986005 //Estimated date of conception [observable entity] 
* include codes from system http://snomed.info/sct where concept is-a #451291000124104 //Adverse reaction caused by zoster vaccine [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #93143009 //Leukemia, disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #399600009 //Lymphoma [finding] 
* include codes from system http://snomed.info/sct where concept is-a #118599009 //Hodgkin's disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #109989006 //Multiple myeloma [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #86406008 //Human immunodeficiency virus infection [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #363346000 //Malignant neoplastic disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #233703007 //Interstitial lung disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #190905008 //cystic fibrosis [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #70995007 //Pulmonary hypertension [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #52448006 //Dimensia [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #41040004 //Complete trisomy 21 syndrome [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #40108008 //Thalassemia [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #62914000 //Cerebrovascular disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #13645005 //Chronic obstructive lung disease [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #87433001 //Pulmonary emphysema [disorder] 
* include codes from system http://snomed.info/sct where concept is-a #413490006 //American Indian or Alaska Native [racial group] 
