#!/usr/bin/env python3
"""Write cicada/lib/generated_files/cvx_displays.dart and mvx_displays.dart from
the CVX and MVX code systems.

The IG publisher validates every Coding.display against the code system's own
display, and reports anything else as "Wrong Display Name". The engine used to
put CDC's short product names ("PCV15") and hand-written group names
("meningococcal, unspecified formulation") in the display; CVX's own displays
are "Pneumococcal conjugate PCV15, polysaccharide CRM197 conjugate, adjuvant,
PF" and "meningococcal ACWY, unspecified formulation". CDC's short name now
goes in CodeableConcept.text.

Source: a $expand of a ValueSet including all of http://hl7.org/fhir/sid/cvx
on tx.fhir.org, which serves the CVX release named in the expansion's
used-codesystem parameter. Run from the repo root:

    python3 cicada_generator/tool/fetch_cvx_displays.py

Writes the TSV next to this script (the source of record, diffable) and the
Dart map the engine reads. Every row is written as it arrives.
"""
import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
TSV = pathlib.Path(__file__).resolve().parent / "cvx_displays.tsv"
DART = ROOT / "cicada" / "lib" / "generated_files" / "cvx_displays.dart"

def fetch(system):
    body = json.dumps({
        "resourceType": "Parameters",
        "parameter": [
            {"name": "count", "valueInteger": 2000},
            {"name": "valueSet", "resource": {
                "resourceType": "ValueSet", "status": "active",
                "compose": {"include": [{"system": system}]}}},
        ],
    })
    raw = subprocess.run(
        ["curl", "-s", "-X", "POST", "https://tx.fhir.org/r4/ValueSet/$expand",
         "-H", "Accept: application/fhir+json", "-H", "Content-Type: application/fhir+json",
         "-d", body],
        capture_output=True, text=True, check=True).stdout
    vs = json.loads(raw)
    if vs.get("resourceType") != "ValueSet":
        sys.exit(f"expand of {system} failed: {raw[:300]}")
    exp = vs["expansion"]
    items = exp.get("contains", [])
    total = exp.get("total")
    if total is not None and total != len(items):
        sys.exit(f"expansion of {system} truncated: {len(items)} of {total}")
    version = next((p.get("valueUri") or p.get("valueString")
                    for p in exp.get("parameter", []) if p["name"] == "used-codesystem"), "?")
    return items, version



def dart_string(text, indent):
    """A single-quoted Dart literal, split into adjacent literals at spaces
    when the line would pass 80 columns (very_good_analysis
    lines_longer_than_80_chars); dart format lays the pieces out and the
    compiler joins them."""
    room = 80 - indent - 4 - 2 - 2
    if len(text) <= room or " " not in text:
        return f"'{text}'"
    pieces, rest = [], text
    while len(rest) > room:
        cut = rest.rfind(" ", 0, room)
        if cut <= 0:
            cut = rest.find(" ")
        if cut <= 0:
            break
        pieces.append(rest[: cut + 1])
        rest = rest[cut + 1 :]
    pieces.append(rest)
    return " ".join(f"'{p}'" for p in pieces)

def write(name, system, items, version):
    tsv = pathlib.Path(__file__).resolve().parent / f"{name}_displays.tsv"
    dart = ROOT / "cicada" / "lib" / "generated_files" / f"{name}_displays.dart"
    up = name.upper()
    with open(tsv, "w") as t, open(dart, "w") as d:
        t.write(f"# {up} {version}, {len(items)} concepts, from tx.fhir.org $expand\n")
        t.write("code\tdisplay\n")
        d.write("// GENERATED by cicada_generator/tool/fetch_cvx_displays.py. Do not edit.\n")
        d.write(f"// {up} {version}, {len(items)} concepts, from tx.fhir.org $expand.\n\n")
        d.write(f"/// {up} code -> the {up} code system's own display.\n")
        d.write(f"const Map<String, String> {name}Displays = <String, String>{{\n")
        def key(c):
            return (0, int(c["code"])) if c["code"].isdigit() else (1, c["code"])
        for c in sorted(items, key=key):
            code, disp = c["code"], (c.get("display") or "").replace("'", "\\'")
            t.write(f"{code}\t{c.get('display')}\n")
            d.write(f"  '{code}': {dart_string(disp, indent=2)},\n")
            t.flush(); d.flush()
            print(name, code, disp, flush=True)
        d.write("};\n")
    subprocess.run(["dart", "format", str(dart)], check=True, capture_output=True)
    print(f"wrote {len(items)} {up} displays ({version}) to {dart}", flush=True)


def items_from_tsv(name):
    """The last fetch's rows, so the Dart can be re-emitted (e.g. after a
    change to dart_string) without asking tx.fhir.org again: --from-tsv."""
    tsv = pathlib.Path(__file__).resolve().parent / f"{name}_displays.tsv"
    lines = tsv.read_text().splitlines()
    version = lines[0].split(",")[0].split()[-1]
    items = [{"code": c, "display": d} for c, d in (l.split("\t", 1) for l in lines[2:])]
    return items, version


if __name__ == "__main__":
    from_tsv = "--from-tsv" in sys.argv
    for name, system in (("cvx", "http://hl7.org/fhir/sid/cvx"), ("mvx", "http://hl7.org/fhir/sid/mvx")):
        items, version = items_from_tsv(name) if from_tsv else fetch(system)
        write(name, system, items, version)
