#!/usr/bin/env python3
"""Write cicada/lib/generated_files/cvx_displays.dart from the CVX code system.

The IG publisher validates every Coding.display against the code system's own
display, and reports anything else as "Wrong Display Name". The engine used to
put CDC's short product names ("PCV15") and hand-written group names
("meningococcal, unspecified formulation") in the display; CVX's own displays
are "Pneumococcal conjugate PCV15, polysaccharide CRM197 conjugate, adjuvant,
PF" and "meningococcal ACWY, unspecified formulation". CDC's short name now
goes in CodeableConcept.text.

Source: a $expand of a ValueSet including all of http://hl7.org/fhir/sid/cvx
on tx.fhir.org, which serves the CVX release named in the expansion's
used-codesystem parameter. Run from the repo root:

    python3 cicada_generator/tool/fetch_cvx_displays.py

Writes the TSV next to this script (the source of record, diffable) and the
Dart map the engine reads. Every row is written as it arrives.
"""
import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
TSV = pathlib.Path(__file__).resolve().parent / "cvx_displays.tsv"
DART = ROOT / "cicada" / "lib" / "generated_files" / "cvx_displays.dart"

body = json.dumps({
    "resourceType": "Parameters",
    "parameter": [
        {"name": "count", "valueInteger": 2000},
        {"name": "valueSet", "resource": {
            "resourceType": "ValueSet", "status": "active",
            "compose": {"include": [{"system": "http://hl7.org/fhir/sid/cvx"}]}}},
    ],
})
raw = subprocess.run(
    ["curl", "-s", "-X", "POST", "https://tx.fhir.org/r4/ValueSet/$expand",
     "-H", "Accept: application/fhir+json", "-H", "Content-Type: application/fhir+json",
     "-d", body],
    capture_output=True, text=True, check=True).stdout
vs = json.loads(raw)
if vs.get("resourceType") != "ValueSet":
    sys.exit(f"expand failed: {raw[:300]}")
exp = vs["expansion"]
items = exp.get("contains", [])
total = exp.get("total")
if total is not None and total != len(items):
    sys.exit(f"expansion truncated: {len(items)} of {total}")
version = next((p.get("valueUri") or p.get("valueString")
                for p in exp.get("parameter", []) if p["name"] == "used-codesystem"), "?")

with open(TSV, "w") as tsv, open(DART, "w") as dart:
    tsv.write(f"# CVX {version}, {len(items)} concepts, from tx.fhir.org $expand\n")
    tsv.write("code\tdisplay\n")
    dart.write("// GENERATED by cicada_generator/tool/fetch_cvx_displays.py. Do not edit.\n")
    dart.write(f"// CVX {version}, {len(items)} concepts, from tx.fhir.org $expand.\n\n")
    dart.write("/// CVX code -> the CVX code system's own display.\n")
    dart.write("const Map<String, String> cvxDisplays = <String, String>{\n")
    for c in sorted(items, key=lambda c: int(c["code"]) if c["code"].isdigit() else 10**6):
        code, disp = c["code"], (c.get("display") or "").replace("'", "\\'")
        tsv.write(f"{code}\t{c.get('display')}\n")
        dart.write(f"  '{code}': '{disp}',\n")
        tsv.flush(); dart.flush()
        print(code, disp, flush=True)
    dart.write("};\n")
print(f"wrote {len(items)} CVX displays ({version}) to {DART}", flush=True)
