#!/usr/bin/env python3
"""Generate the CDSi observation CodeSystem from CDC's supporting data.

It was maintained by hand and drifted 27 concepts behind: CDC 4.65-508 carries
278 observations, the IG carried 251, and none of ours was absent from CDC's.
Hand-maintaining a list CDC publishes is the defect; this reads their XML.

Usage: generate_obs_codesystem.py <ScheduleSupportingData.xml> <out.fsh>
"""
import html
import re
import sys

HEADER = '''// GENERATED by cicada_generator/tool/generate_obs_codesystem.py from
// Version_{version}/XML/ScheduleSupportingData.xml — do not edit by hand.
//
// The display is CDC's own observationTitle. The code is their observationCode,
// kept as a three-character string with its leading zeros, because that is how
// the supporting data and every test case write it.
CodeSystem:  CdsiObservationCodes
Id: cdsi-observation-codes
Title: "CDSI Observation Codes"
Description:  "Observations and Conditions that are important to indications or contraindications in vaccine forecasting"
* ^caseSensitive = true
* ^content = #complete
'''


def main(xml_path, out_path):
    xml = open(xml_path, encoding='utf-8').read()
    version = re.search(r'Version_([\d.\-]+)', xml_path)
    seen, rows = set(), []
    for m in re.finditer(
            r'<observationCode>(\d+)</observationCode>\s*'
            r'<observationTitle>(.*?)</observationTitle>', xml, re.S):
        code, title = m.group(1), ' '.join(html.unescape(m.group(2)).split())
        if code in seen:
            continue
        seen.add(code)
        rows.append((code, title.replace('"', "'")))
    rows.sort(key=lambda r: r[0])

    # display is the observation title, definition is CDC's text for it.
    # The hand-written file had `* #003 "003"` with the title as the
    # definition, so every display was just the code repeated, which the
    # publisher reports as CONCEPTMAP_GROUP_TARGET_DISPLAY_INVALID against
    # every element of the ConceptMap.
    body = ''.join(f'* #{c} "{t}"\n' for c, t in rows)
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(HEADER.format(version=version.group(1) if version else 'unknown'))
        f.write(body)
    print(f'{len(rows)} observations written to {out_path}')


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
