#!/usr/bin/env python3
"""Generate the ConceptMaps for the code systems CDC does not publish.

CDC's supporting data carries SNOMED, CVX and PHIN VS only. Every ICD-10-CM,
LOINC, RxNorm and CPT code the engine matches on comes from
crosswalk/observation_crosswalk.json, which is ours. The IG published 17 ICD-10
elements against the 295 codes in that file, so the map is generated from it.

Usage: generate_crosswalk_maps.py <crosswalk.json> <observation_titles.xml> <out_dir>
"""
import html
import json
import os
import re
import sys

CDSI_CS = 'http://fhirfli.dev/fhir/ig/cicada/CodeSystem/cdsi-observation-codes'
CDSI_VS = 'http://fhirfli.dev/fhir/ig/cicada/ValueSet/cdsi-observation-codes-vs'

SYSTEMS = {
    'ICD10CM': ('Icd10ToCdsiObservation', 'ICD-10-CM', 'http://hl7.org/fhir/sid/icd-10-cm',
                'http://fhirfli.dev/fhir/ig/cicada/ValueSet/vaccine-condition-codes-icd10',
                'cm_icd10_to_cdsi.fsh'),
}


def main(crosswalk_path, xml_path, out_dir):
    cross = json.load(open(crosswalk_path, encoding='utf-8'))
    xml = open(xml_path, encoding='utf-8').read()
    titles = {m.group(1): ' '.join(html.unescape(m.group(2)).split()).replace('"', "'")
              for m in re.finditer(
                  r'<observationCode>(\d+)</observationCode>\s*'
                  r'<observationTitle>(.*?)</observationTitle>', xml, re.S)}

    for key, (inst, label, system, source_vs, fname) in SYSTEMS.items():
        lines, n, seen = [], 0, set()
        for obs_code in sorted(k for k in cross if not k.startswith('_')):
            for entry in cross[obs_code].get(key, []):
                code, text = entry['code'], entry.get('text', '').replace('"', "'")
                if code in seen:
                    lines.append(f'// {code} also cited by observation {obs_code}')
                    continue
                seen.add(code)
                title = titles.get(obs_code, obs_code)
                lines.append(f'\n// {obs_code} - {title}')
                lines.append(f'* group[=].element[+].code = #{code}')
                lines.append(f'* group[=].element[=].display = "{text}"')
                lines.append(f'* group[=].element[=].target[+].code = #{obs_code}')
                lines.append(f'* group[=].element[=].target[=].display = "{title}"')
                lines.append('* group[=].element[=].target[=].equivalence = #equivalent')
                n += 1

        header = f'''// GENERATED by cicada_generator/tool/generate_crosswalk_maps.py from
// crosswalk/observation_crosswalk.json — do not edit by hand.
//
// CDC's supporting data carries SNOMED, CVX and PHIN VS only, so every
// {label} code here is ours. The hand-written version carried 17 elements.
Instance: {inst}
InstanceOf: ConceptMap
Usage: #definition
Title: "{label} to CDSi Observation Code Map"
Description: "Maps {label} codes to CDSi observation codes used in immunization decision support. Generated from the cicada crosswalk."
* status = #active
* experimental = false
// ValueSets, not CodeSystems: R4 binds ConceptMap.source[x] to a ValueSet.
* sourceCanonical = "{source_vs}"
* targetCanonical = "{CDSI_VS}"

* group[+].source = "{system}"
* group[=].target = "{CDSI_CS}"
'''
        out = os.path.join(out_dir, fname)
        with open(out, 'w', encoding='utf-8') as f:
            f.write(header)
            f.write('\n'.join(lines) + '\n')
        print(f'{n} {label} codes mapped -> {out}')


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
