#!/usr/bin/env python3
"""Generate the SNOMED->CDSi ConceptMap from CDC's own supporting data.

The map was hand-listed and carried 11 elements while CDC publishes 275 SNOMED
codings across 150 of their 278 observations. Everything in it is data CDC
already gives us, so it is generated, not maintained.

Also fixes two defects the hand-written file carried:

  * `sourceUri`/`targetUri` named code systems. R4 wants ValueSets there, which
    is the CONCEPTMAP_VS_NOT_A_VS error, so both sides now name ValueSets.
  * the CDSi side used https://www.cdc.gov/vaccines/programs/iis/cdsi, a third
    URL for a concept space our own CodeSystem already publishes under
    http://fhirfli.dev/fhir/ig/cicada/CodeSystem/cdsi-observation-codes.

Usage: generate_concept_maps.py <ScheduleSupportingData.xml> <out.fsh>
"""
import html
import re
import sys

CDSI_CS = 'http://fhirfli.dev/fhir/ig/cicada/CodeSystem/cdsi-observation-codes'
CDSI_VS = 'http://fhirfli.dev/fhir/ig/cicada/ValueSet/cdsi-observation-codes-vs'
SNOMED_VS = 'http://fhirfli.dev/fhir/ig/cicada/ValueSet/vaccine-condition-codes-snomed'

HEADER = '''// GENERATED by cicada_generator/tool/generate_concept_maps.py from
// ScheduleSupportingData.xml — do not edit by hand.
//
// Every element here is a <codedValue> CDC publishes against an observation.
// The hand-written version carried 11 of them.
Instance: SnomedToCdsiObservation
InstanceOf: ConceptMap
Usage: #definition
Title: "SNOMED CT to CDSi Observation Code Map"
Description: "Maps SNOMED CT codes to CDSi observation codes used in immunization decision support. Generated from CDC's supporting data."
* status = #active
* experimental = false
// ValueSets, not CodeSystems: R4 binds ConceptMap.source[x] to a ValueSet.
* sourceCanonical = "{snomed_vs}"
* targetCanonical = "{cdsi_vs}"

* group[+].source = "http://snomed.info/sct"
* group[=].target = "{cdsi_cs}"
'''


def main(xml_path, out_path):
    xml = open(xml_path, encoding='utf-8').read()
    obs = re.findall(
        r'<observation>\s*<observationCode>(\d+)</observationCode>\s*'
        r'<observationTitle>(.*?)</observationTitle>(.*?)</observation>', xml, re.S)

    lines, n, seen = [], 0, set()
    for code, title, body in obs:
        title = ' '.join(html.unescape(title).split()).replace('"', "'")
        for cm in re.finditer(
                r'<codedValue>\s*<code>([^<]+)</code>\s*<codeSystem>SNOMED</codeSystem>\s*'
                r'<text>(.*?)</text>', body, re.S):
            src, disp = cm.group(1).strip(), ' '.join(html.unescape(cm.group(2)).split())
            # A SNOMED concept can be cited by more than one observation; the
            # first wins, and the rest are recorded so the loss is visible.
            if src in seen:
                lines.append(f'// {src} also cited by observation {code}')
                continue
            seen.add(src)
            lines.append(f'\n// {code} - {title}')
            lines.append(f'* group[=].element[+].code = #{src}')
            lines.append(f'* group[=].element[=].display = "{disp.replace(chr(34), chr(39))}"')
            lines.append(f'* group[=].element[=].target[+].code = #{code}')
            lines.append(f'* group[=].element[=].target[=].display = "{title}"')
            lines.append('* group[=].element[=].target[=].equivalence = #equivalent')
            n += 1

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(HEADER.format(cdsi_cs=CDSI_CS, cdsi_vs=CDSI_VS, snomed_vs=SNOMED_VS))
        f.write('\n'.join(lines) + '\n')
    print(f'{n} SNOMED codes mapped, across {len(obs)} observations')


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
